### ISSUE TITLE
[Question] for bot.

### ISSUE THREAD

**Issue by xSuspect** [slow/nitro-sniper#1]
Hi, I also tested this project and it is moving slowly. [below is an example]
``[Sniper] Already Redeemed - Code: 9kQnlsexrj5dNxMy - 'Random' (Random#0001) - 370ms``
``[Sniper] Already Redeemed - Code: M7fHqsex0UyVCvT5 - Random' (Random#0001) - 133ms``

what you need in the project to change to move faster
` Math.floor(Math.random() * (3000 - 1000 + 1)) + 1000);` this ?

thanks.

**Comment by slow** [comment]
Removing that will cause all clients to be logged in at the same time, and Discord's gateway would refuse the websocket connection if multiple tokens are used, that generates a random delay to avoid getting refused from the websocket.

As for your response time being high make sure your heroku application is set to United States as the region and keep in mind that discord has 2 passes to redeeming a  code, what's happening there is that you were really close to claiming the code but someone got through the second pass before you, which caused high ms as the first pass was processed, that's nothing to worry about as it will still snipe properly, response time varies a LOT depending on the situation but don't worry about it. The sniper is the fastest it can be in JavaScript.

**Comment by xSuspect** [comment]
thanks for the quick response.
and yes I was on Europe, and discord servers in America, possible to have an impact.
and I didn't understand with `webhookUrl=""` [is the link in the picture below?]
![webhook](https://user-images.githubusercontent.com/45514952/103144059-a3ab2400-472b-11eb-9db0-e3105276ced9.png)

**Comment by slow** [comment]
Yes it is indeed the link below, and yes the reason it was slow for you is because you are on Europe servers and discord servers are in NA. Happy to help.
