### ISSUE TITLE
[Bug] Giveaway Settings

### ISSUE THREAD

**Issue by CZxqE1Vf35** [slow/nitro-sniper#11]
i think the bot does not "respect" values set inside of the giveaway key. i have "giveaway": {"enabled": false} but the webhook sends "Giveaway Won" after reacting to any giveaway without even actually winning. it also reacted to a blacklisted word and dm'd the hoster.

**Comment by slow** [comment]
I'll have a look for you.

**Comment by slow** [comment]
Let me know if you still face any of those issues.
