### ISSUE TITLE
Bro i have a question

### ISSUE THREAD

**Issue by nichevulcan20** [slow/nitro-sniper#123]
**Can I set the giveaway joiner with alt support? like**
- my alts will join lots of servers and their giveaways
- and when my alts win and get nitro, will redeem that to the main account.
- my main account doesn't be required to join shit servers right?

**Comment by PoloNX** [comment]
It's stupid, if your alt account win the giveaway, and your main dm the guy. The guy will say "you haven't win the giveaway, it's "your alt account name" who win the giveaway.

**Comment by InimicalPart** [comment]
> It's stupid, if your alt account win the giveaway, and your main dm the guy. The guy will say "you haven't win the giveaway, it's "your alt account name" who win the giveaway.

I think they meant that the alt dms the giveaway hoster and when it gets the nitro link it redeems it on the main account

**Comment by nichevulcan20** [comment]
> It's stupid, if your alt account win the giveaway, and your main dm the guy. The guy will say "you haven't win the giveaway, it's "your alt account name" who win the giveaway.

AYE BRO im trying to say-

Alt will win, alt will dm to the host, once the host gives nitro to **alt**, the **alt will redeem that code to the main account**

**Comment by nichevulcan20** [comment]
> > It's stupid, if your alt account win the giveaway, and your main dm the guy. The guy will say "you haven't win the giveaway, it's "your alt account name" who win the giveaway.
> 
> I think they meant that the alt dms the giveaway hoster and when it gets the nitro link it redeems it on the main account

yes bro :)

**Comment by PoloNX** [comment]
> > It's stupid, if your alt account win the giveaway, and your main dm the guy. The guy will say "you haven't win the giveaway, it's "your alt account name" who win the giveaway.
> 
> 
> 
> AYE BRO im trying to say-
> 
> 
> 
> Alt will win, alt will dm to the host, once the host gives nitro to **alt**, the **alt will redeem that code to the main account**

Yeah but when the alt receive the nitro link, the sniper will works and redeem the nitro code.

**Comment by InimicalPart** [comment]
> > > It's stupid, if your alt account win the giveaway, and your main dm the guy. The guy will say "you haven't win the giveaway, it's "your alt account name" who win the giveaway.
> > 
> > I think they meant that the alt dms the giveaway hoster and when it gets the nitro link it redeems it on the main account
> 
> yes bro :)

If I'm not wrong then it already works like that, that's why you put the tokens in "alts" in the .env file. And that's probably why the sniper won't work without a main token. The options `main`, `alts` and `both` probably are there to select where it should "find" the token from. Like `main` will only search for tokens on the main account and redeem them. But `alts` will search on the alt accounts and redeem on the main (recommended as it lowers the chance of your main getting banned) and `both` which searches for codes on the main and the alt accounts.

**Comment by slow** [comment]
This is the exact functionality that the sniper has.
Any other questions on this issue were answered by @InimicalPart

**Comment by nichevulcan20** [comment]
> This is the exact functionality that the sniper has.
> Any other questions on this issue were answered by @InimicalPart

thankyou bro but when deploying sniper do i have to se `both` ?
and if i use both then if alt gets nitro then will the alt redeem to main after winning giveaway?

**Comment by InimicalPart** [comment]
`Both` will use giveaway sniper on the main account and the alt accounts. If you select `alts` it will run giveaway sniper on the alts and redeem the codes on the main account, all options will redeem the code on the main account

**Comment by nichevulcan20** [comment]
> `Both` will use giveaway sniper on the main account and the alt accounts. If you select `alts` it will run giveaway sniper on the alts and redeem the codes on the main account, all options will redeem the code on the main account
> 
> The best option in my opinion is `alts`

TY BRO i was viewing the modes question and was viewing ur answer there ur so good bro ty bro ty

**Comment by nichevulcan20** [comment]
> `Both` will use giveaway sniper on the main account and the alt accounts. If you select `alts` it will run giveaway sniper on the alts and redeem the codes on the main account, all options will redeem the code on the main account
> 
> The best option in my opinion is `alts`

but bro one question... my friend got disabled because discord caught him and he said this was because of high pings... if ur using the sniper, is ur experience safe?

**Comment by InimicalPart** [comment]
My recommendation to this is:
- have a maximum of 10 giveaway servers
- **Use an alt!**

This sniper avoides duplicate codes so if anyone spams the same code, the sniper will only check it once, next time it will just ignore that code.
