### ISSUE TITLE
[Bug] stopped working

### ISSUE THREAD

**Issue by iAnvar** [slow/nitro-sniper#126]
stopped working few hours ago, please check it. I get an error when trying to run on Heroku. Settings is 100% correct.
![image](https://user-images.githubusercontent.com/84909834/121079802-113ba000-c7f4-11eb-84e9-6313f5e67cca.png)

**Comment by slow** [comment]
Read the errror...

**Comment by InimicalPart** [comment]
This is because in the config var you copied the contents of the .env file from your computer. you need to navigate to settings in heroku, press "reveal config vars" and remove `settings=` at the beggining. Then it should work
