### ISSUE TITLE
Unknown Response

### ISSUE THREAD

**Issue by WildKing2G** [slow/nitro-sniper#131]
Hi, sorry for the hour, i have this issue when bot try to claim the code.

• Unknown Response | Payment source required to redeem gift. | Code: 57RB7bH3bTkksK4x2zKZ4tf5 | : xxxxxx ៸៸ xxxxxxx > #﹒txt | xxxx#xx69 | 64ms

I have my credit card in my account, and paypal account too...

**Comment by slow** [comment]
The credit card/payment method should be on your main account, the sniper handles getting the payment method and using it so that shouldn't be a problem. Do you have the payment method on your main account?

**Comment by WildKing2G** [comment]
Thats rare, but yes. I only use my main acc.

**Comment by WildKing2G** [comment]
![1](https://user-images.githubusercontent.com/85716484/121621775-38d47780-ca43-11eb-90ae-a1465c0bbc5a.PNG)
![2](https://user-images.githubusercontent.com/85716484/121621787-3b36d180-ca43-11eb-982d-058e5b090391.PNG)

**Comment by WildKing2G** [comment]
This is new

![3](https://user-images.githubusercontent.com/85716484/121625388-c1561680-ca49-11eb-9d9a-b95ba5c66c7b.PNG)

**Comment by godpow** [comment]
This happens because of the epic games nitro thing. It only allows people that never had nitro before to redeem it. @WildKing2G

**Comment by InimicalPart** [comment]
Is it possible you have a proxy installed? (I don't know if it's possible to have a proxy on Heroku but I'm asking to be sure)

**Comment by slow** [comment]
> This is new
> 
> ![3](https://user-images.githubusercontent.com/85716484/121625388-c1561680-ca49-11eb-9d9a-b95ba5c66c7b.PNG)

This was fixed.

**Comment by slow** [comment]
Closing as the sniper grabs the proper info. 
This is either the following:
- Human error
- Wrongly configured sniper
- Discord being dumb
![image](https://user-images.githubusercontent.com/73202350/121635729-a4880600-ca7e-11eb-93b9-ce8f718c1b94.png)
