### ISSUE TITLE
[Bug Report] Payment Source Required To Redeem Gift

### ISSUE THREAD

**Issue by ShyLex** [slow/nitro-sniper#133]
Every time the sniper attempts to redeem a code this error occurs: "Unknown Response | Payment source required to redeem gift."

This has been happening for a while and this new update for me hasn't fixed it somehow, also I've put a payment source in my account and it still happens.

I'm using Heroku by the way if it helps.

**Comment by Imploded** [comment]
Discord has updated their API and its a bug with all sniper :/

**Comment by ShyLex** [comment]
> Discord has updated their API and it's a bug with all snipers :/

Ah, I hope this gets fixed soon

**Comment by InimicalPart** [comment]
API hasn't updated tho, but I'll investigate the problem.

**Comment by InimicalPart** [comment]
So, I've looked around a bit and nothing seems off, the "Payment Source Required To Redeem Gift" is coming from the body of the API webpage directly and not from the code as you can see below.
![image](https://user-images.githubusercontent.com/37552123/121771711-5a338180-cb71-11eb-916a-7939747a8f89.png)
Some possible solutions to try:
- Get the latest version of nitro-sniper
- Make sure your payment method is set to default
- Check if issue [#131](https://github.com/slow/nitro-sniper/issues/131#issuecomment-859279262) solves your problem.

> If you liked my response, please react with a heart ❤️:)

**Comment by Zvakun** [comment]
Just happened to me twice. I even reinstalled the sniper.

**Comment by Niraj-Dilshan** [comment]
Im also getting these issue i am using latest version of the sniper
Any Idea How to fix this?

**Comment by InimicalPart** [comment]
@Zvakun @Niraj-Dilshan Have you tried the solution I gave above?

**Comment by Niraj-Dilshan** [comment]
> @Zvakun @Niraj-Dilshan Have you tried the solution I gave above?

I didt get it should i include that code segment when installing?

**Comment by InimicalPart** [comment]
> > @Zvakun @Niraj-Dilshan Have you tried the solution I gave above?
> 
> I didt get it should i include that code segment when installing?

No, That code piece was to show that the "Payment Source Required To Redeem Gift" is coming from discord. That means that discord thinks you don't have a payment method set in your account. 

You can try if these steps work for you:

> Some possible solutions to try:
> 
> * Get the latest version of nitro-sniper
> * Make sure your payment method is set to default
> * Check if issue [#131](https://github.com/slow/nitro-sniper/issues/131#issuecomment-859279262) solves your problem.

> If you liked my response, please react with a heart ❤️:)

**Comment by Niraj-Dilshan** [comment]
I have checked it again i have assigned payment method from my main account and its set to default. 
![image](https://user-images.githubusercontent.com/61787989/121805257-196a6400-cc68-11eb-9a58-0ebb00778b00.png)

**Comment by InimicalPart** [comment]
It's also possible that the code you were trying to snipe was the Epic Games x Discord nitro code, It's a bit problematic when it comes to those and the event is soon over so we won't be fixing it. 

If the nitro code is long like `XsGPstZwf7xfVN49WjdzMb3t` then it's probably the Epic Games x Discord code.

**Comment by Zvakun** [comment]
can now confirm that it is epic games codes that make it display the error after testing with my own epic games nitro codes
- first is a random code it tried to snipe in a discord server
- second code is an epic games code I put into a chat from an alt

![JZm365ds](https://user-images.githubusercontent.com/73380376/121826979-17ac9a80-cc80-11eb-9696-7d94ff559246.png)

**Comment by InimicalPart** [comment]
The event is almost over and all Epic Games x Discord nitro codes will expire, I think it's actually today so this error should stop appearing in some time.

> If you liked my response, please react with a heart ❤️:)

**Comment by OTKirito1** [comment]
was this fixed? I'm still getting this error on the latest version
-Epic Games x Discord nitro codes don't look like normal gift codes , why would it match the regex

**Comment by InimicalPart** [comment]
Normal nitro codes are between 16 and 25 characters, that’s what the regex is looking for.

**Comment by OTKirito1** [comment]
the regex also looks for the "discord.gift" part
> /(discord.gift|discord.com|discordapp.com/gifts)/\w{16,25}/g
the Epic Games x Discord codes dont have that..
"https://discord.com/billing/promotions/RNgGBcA5GqsXZ8jP5SbZFMXp"

**Comment by InimicalPart** [comment]
Actually, after some review, even I'm really unsure what's going on, I just took a look at the regex again and you're right, It shouldn't be triggering the regex. As you can see below, the test line didn't trigger the regex.
![image](https://user-images.githubusercontent.com/37552123/123184310-b6f93b00-d493-11eb-8cdb-cfc230f1788e.png)
When writing this comment I think I got an explanation, People change the `https://discord.com/billing/promotions/` to `discord.gift/`. discord.gift will trigger the regex. People do this to make the little box with the nitro information show up, which will convince more users that the code is real and the entire giveaway is real. Normal users don't pay attention to the code just that it is nitro, And I've tested this myself. and this does work:
![image](https://user-images.githubusercontent.com/37552123/123184660-69c99900-d494-11eb-9bde-6a0f50792de8.png)

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by OTKirito1** [comment]
that should trigger `Invalid code`, not `Payment Source Required To Redeem Gift`
idk too

**Comment by InimicalPart** [comment]
Well that comes from discords API. And the code isn't invalid. It works. Although you need a payment method to claim these epic codes.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by OTKirito1** [comment]
it's not claimed the same way as gifts, you need to go through a process not just have a payment method 🤨

**Comment by InimicalPart** [comment]
It can be claimed using discord.gift. And with normal gifts, you usually don't need a payment method. But you need it with the epic one for some reason. The process is just to press "claim", nothing else.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by OTKirito1** [comment]
what!! with the promo code, you need to paste the link in the browser and press next next and claim.
u telling me you can just take the last part in `https://discord.com/billing/promotions/xxxx`
and make it `discord.gift/xxxx` and it will work?

**Comment by NotVinnny** [comment]
Not sure how the sniper usually handles claiming nitros but it might have to do with the process of pressing things after claiming on the embed.

**Comment by NotVinnny** [comment]
It's also entirely possible that the codes are just BS and aren't supposed to work anyway.

**Comment by OTKirito1** [comment]
> It's also entirely possible that the codes are just BS and aren't supposed to work anyway.

then it should get invalid..

**Comment by NotVinnny** [comment]
Yeah, it's all very weird/inconsistent but I did test it and it did claim a legitimate code so I have no idea what's going on

**Comment by OTKirito1** [comment]
> It can be claimed using discord.gift. And with normal gifts, you usually don't need a payment method. But you need it with the epic one for some reason. The process is just to press "claim", nothing else.
> 


Invalid Code | Code: GTtKyMyyHVvUJhC44vrHvWQg
just tested the promo codes, it returned invalid lol
did you test before saying that ?

**Comment by NotVinnny** [comment]
Inconsistent. maybe future update will see more clear cut error messages

**Comment by InimicalPart** [comment]
> what!! with the promo code, you need to paste the link in the browser and press next next and claim.
> u telling me you can just take the last part in `https://discord.com/billing/promotions/xxxx`
> and make it `discord.gift/xxxx` and it will work?

Correct.
> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by InimicalPart** [comment]
> Not sure how the sniper usually handles claiming nitros but it might have to do with the process of pressing things after claiming on the embed.

It sends a request to the Discord API with the token that you want to claim this code, then discord does the stuff it does and sends back information so you know if it did it or not. The bot needs your token to talk to Discord API and tell it that you are the one requesting the claim. If you don't provide a token, it will not work as Discord will just return `401: Unauthorized`

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by WSrujan** [comment]
Payment method error is due to epic game promotion which ended on 24 June and nitro code stays valid for 30 days so after that there will not be this error. This is my experience from previous discord promotion
