### ISSUE TITLE
Just a lil question about main status

### ISSUE THREAD

**Issue by ItzBoiz** [slow/nitro-sniper#137]
hey can i set that to "invisible" there?
![image](https://user-images.githubusercontent.com/85618839/121889125-75032300-cd36-11eb-86e1-cddb2713fdfb.png)

and if not then, before exiting discord, do i have to set my status to invisible and then when im out, im invisible right?

**Comment by slow** [comment]
![image](https://user-images.githubusercontent.com/73202350/121890811-a964e800-cd12-11eb-9a64-c21313a5845b.png)
😐

**Comment by ItzBoiz** [comment]
> ![image](https://user-images.githubusercontent.com/73202350/121890811-a964e800-cd12-11eb-9a64-c21313a5845b.png)
> 😐

omg bruh

**Comment by InimicalPart** [comment]
xD
