### ISSUE TITLE
pleas enhance the configuration of the sniper on heroku

### ISSUE THREAD

**Issue by ItzBoiz** [slow/nitro-sniper#138]
im seeing this idk what i ruined
![image](https://user-images.githubusercontent.com/85618839/121892122-f3ad8f80-cd39-11eb-8244-934008a09baf.png)

but please make it easier to deploy, like GiorgioBrux does:
![image](https://user-images.githubusercontent.com/85618839/121892226-15a71200-cd3a-11eb-9159-f7800acc1694.png)

there is a field in which we can enter the variables, without ruining the code

**Comment by slow** [comment]
There's too many variables to do that and heroku doesn't sort the variables properly. I'm not planning on changing the configuration.

**Comment by ItzBoiz** [comment]
ok

**Comment by ItzBoiz** [comment]
ok so but..
what is wrong with this code please fix

`{
   tokens: {
      // Main Token
      main: 'private', 
      // Alt Tokens
      alts: [
         'private',
         'private'
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: 'alts',
   /* 
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: '',
      // The status the logged in alts will have
      alts: 'default'
   },  
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 2,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 24
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true, 
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Message to DM the host
      dmMessage: 'YES I WON!!',
      // How long to wait to DM (in seconds)
      dmDelay: 4, 
      // Blacklisted words for giveaway prizes
      blacklistedWords: [ 
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: true, 
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: false,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds) 
         max: 20 
      },
      members: {
         // The minimum member count the server should have
         min: 1500, 
         // The maximum member count the server should have
         max: 50000 
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours) 
      cooldown: 6 
   },
   webhook: {
      // URL to fire webhook to for notifications
      url: 'private,
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: false, 
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: false, 
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: false,
         // Fire webhook on giveaway win (true/false) 
         giveawayWin: true,
         // Fire webhook on invite join (true/false) 
         inviteJoin: false 
      }, 
      mentionEveryone: { 
         // Mention on invalid code (true/false)
         codeInvalid: false, 
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false) 
         codeSuccess: true, 
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false) 
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false 
      }
   }
}`

**Comment by slow** [comment]
@ItzBoiz You missed a quote here: 
![image](https://user-images.githubusercontent.com/73202350/121948854-b2c07580-cd4f-11eb-961b-782d89838ad9.png)
```js
{
  tokens: {
    main: 'private',
    alts: [
      'private',
      'private',
    ],
  },
  mode: 'alts',
  status: {
    main: '',
    alts: 'default',
  },
  nitro: {
    max: 2,
    cooldown: 24,
  },
  giveaway: {
    enabled: true,
    delay: 30,
    dm: true,
    dmMessage: 'YES I WON!!',
    dmDelay: 4,
    blacklistedWords: [
      'bot',
      'test',
      'ban',
    ],
    whitelistOnly: true,
    whitelistedWords: [
      'nitro',
    ],
    blacklistedServers: [
      '',
    ],
  },
  invite: {
    enabled: false,
    delay: {
      min: 10,
      max: 20,
    },
    members: {
      min: 1500,
      max: 50000,
    },
    max: 10,
    cooldown: 6,
  },
  webhook: {
    url: 'private',
    enabled: {
      codeInvalid: false,
      codeAlreadyRedeemed: false,
      codeSuccess: true,
      giveawayEntered: false,
      giveawayWin: true,
      inviteJoin: false,
    },
    mentionEveryone: {
      codeInvalid: false,
      codeAlreadyRedeemed: false,
      codeSuccess: true,
      giveawayEntered: false,
      giveawayWin: true,
      inviteJoin: false,
    },
  },
}
```

**Comment by slow** [comment]
Next time use this to see what you've done wrong: https://jsonformatter.org/json5-formatter

**Comment by ItzBoiz** [comment]
thanks
