### ISSUE TITLE
[Bug] I don't win giveaway yet bot still dms host

### ISSUE THREAD

**Issue by JonasBBX** [slow/nitro-sniper#14]
This is a weird bug and they could suspect me if it keeps spamming them after im not even winning please could you look into this

**Comment by slow** [comment]
Turn it off for now, i'll look into it. Could you please check what giveaway bot they're using?

**Comment by slow** [comment]
Also, is this happening on the latest commit?

**Comment by JonasBBX** [comment]
> Also, is this happening on the latest commit?

(GiveawayBot)) the one everyone uses

and as for the second question im not quite sure what you mean sorry im not english

**Comment by JonasBBX** [comment]
> Also, is this happening on the latest commit?

if you meant it was on the latest update then im not sure cause i only started using it today since its a lot fast then other snipers :)

**Comment by slow** [comment]
Yes i did mean the latest update, i recently made a few fixes regarding the giveaway system so could you please make sure you're on the latest update.

If you encounter any other issues or the same issue please let me know.

**Comment by JonasBBX** [comment]
did you update it for Heroku cause thats whats its happening on

**Comment by slow** [comment]
When you click the deploy button, heroku automatically grabs the latest version. After you've deployed, if i make any changes it won't update so you'll have to re-deploy.

**Comment by JonasBBX** [comment]
okay ill re-deploy again and have a look.

**Comment by JonasBBX** [comment]
mhm still happening
