### ISSUE TITLE
Pls fix the invite sniper

### ISSUE THREAD

**Issue by ItzBoiz** [slow/nitro-sniper#142]
why is it broken :/
my alt got disabled for using selfbot...
i mean all things are safe but not the invite sniper

**Comment by Ender786** [comment]
There is no way this can be fixed, just don't use the invite sniper, you are just going to have to join servers yourself

**Comment by Serial-Comma** [comment]
> There is no way this can be fixed, just don't use the invite sniper, you are just going to have to join servers yourself

why do you say 'no way this can be fixed'

**Comment by 265866** [comment]
@ItzBoiz @Serial-Comma There's always a risk associated with selfbotting, you can get banned for even just using the regular sniper if discord makes a security update. There's no way to get it risk free

**Comment by InimicalPart** [comment]
The invite sniper is not really recommended to use as it will probably get your account banned in a few hours to days.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)
