### ISSUE TITLE
[Feature Request] DM sniper timer & Multiple dm support

### ISSUE THREAD

**Issue by ItzBoiz** [slow/nitro-sniper#143]
I request/suggest to add two features. and i explained them below, pls respond!

**Allow to send multiple message in dms of host**
I've checked my alt and saw that it dmed to 2 hosts but some replied "send one more message to prove ur not a robo" 
both the hosts were in same server. also banned from that server. soo is it possible to add new feature?

**Add redeem time? in dms of host**
when the code gets sniped in dms its really fast, the host acts like "wtf" this man claimed and didnt even got badge cuz yeah it redeems to main. soo what if u add an optional timer like 1 - 2s to claim nitro from **dms**

second suggestion is optional cuz i think it would be hard to add or it would be boring

**Comment by InimicalPart** [comment]
Nothing is really "boring", everything is exciting and has its own strengths in its own way. About the first option, that might be hard to add as the person can use many different keywords to check if you are a robot. This isn't too hard when getting **bot** messages as they are programmed to say things. And you can easily just get all valid responses from a bot.

About the second one, this has its strengths and weaknesses, the strength with this is that they have a lower chance of noticing, but. When you get a code it's best to catch it as fast as possible to avoid other people getting the code or to just avoid the code owner/giveaway hoster claiming the code for themselves (trying to scam you). It's also unlikely that the person will notice that the code got claimed so fast. I believe that the code embed will not update for a while, and the owner has a small chance of checking your profile constantly,

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)
