### ISSUE TITLE
[Question] More and more server 

### ISSUE THREAD

**Issue by PoloNX** [slow/nitro-sniper#144]
If I have 300 servers in all with my alts accounts. My sniper will be more slow ?

**Comment by 265866** [comment]
@PoloNX from my understanding, yes, the more servers it watches the slower it will be, but if you're using a small amount such as 300 servers, it won't make a difference at all, it's more like once you start getting to the 10-20k server range I think

**Comment by InimicalPart** [comment]
The sniper will be slow for every server you have, you'll probably not notice as it gets a very very tiny bit slower. But you might notice like @265866 said when you get to the higher numbers.
