### ISSUE TITLE
[Feature Request] Automatically update code on heroku

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#147]
Please make Heroku update automatically so i don't need create one and delete old one every time  when code is updated
or i just dont know how to do it

**Comment by InimicalPart** [comment]
I don't think that's possible, and it doesn't really matter, as Heroku has flagged the code as violating and the code will not run on Heroku until we manage to get a solution. Check #149 for more information.

**Comment by slow** [comment]
I don't believe this is possible unless we git clone the sniper on each start which would be really inefficient and would make other forks unusable. This will just complicate things.

**Comment by uhIgnacio** [comment]
seems to be this sniper doenst use heroku anymore and changed to replit

**Comment by slow** [comment]
This has been added for repl.it

The sniper no longer supports heroku so i will close this.
