### ISSUE TITLE
[Bug Report] Segmentation fault on startup

### ISSUE THREAD

**Issue by RandomGuy0001** [slow/nitro-sniper#148]
**Describe the bug**
Whenever I run node . I get a segmentation fault error after it logs in.
Second time I ran it gave segmentation fault error without logging in.
Node version: v14.17.1
Platform: linux ARMv7 (raspberry pi 4)
![image](https://user-images.githubusercontent.com/75224622/123629392-89561e00-d814-11eb-811f-1c2cea906315.png)
![image](https://user-images.githubusercontent.com/75224622/123629473-9bd05780-d814-11eb-82fc-359d5ad3dcb3.png)

**Comment by slow** [comment]
This seems to be a linux specific error and noone else seems to have this issue. I'll close this for now. If anyone else has this issue reply to this.
