### ISSUE TITLE
[Bug Report] Heroku flagged the code

### ISSUE THREAD

**Issue by editsellar** [slow/nitro-sniper#149]
When deploying app to Heroku I get an issue saying "Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy." is there any way to fix this issue?

**Comment by realdep** [comment]
Same here. Looks like they flagged the code.

**Comment by InimicalPart** [comment]
Yeah, it looks like it, I took a quick look at the [Acceptable Use and External-Facing Services Policy](https://c1.sfdcstatic.com/content/dam/web/en_us/www/documents/legal/Agreements/policies/ExternalFacing_Services_Policy.pdf) and it looks like it falls this category: 
![image](https://user-images.githubusercontent.com/37552123/124029594-9a11ba00-d9f5-11eb-9dfe-d6d6f8104485.png)
Unfortunately, I think there is nothing we can do to fix that, although I will think of a solution, if I come up with one, I will update you.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by SebaBlamey** [comment]
How soon do you think you can solve it? :(

**Comment by InimicalPart** [comment]
I really don't know, as the source code got flagged and we don't really know what got flagged and how we can fix it. So honestly speaking, few weeks at least.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by realdep** [comment]
Vedza's sniper works fine on heroku, why on hell did they flag this one?

**Comment by editsellar** [comment]
Update: seems the older version of the sniper works better than ever with heroku!

**Comment by WildKing2G** [comment]
> 
> 
> Update: seems the older version of the sniper works better than ever with heroku!

how can i use the older version again with heroku?

**Comment by realdep** [comment]
you can self deploy the code, it works fine

**Comment by frosDfurret** [comment]
pretty simple stuff.
1. fork this repository.
2. login to heroku.
3. copy and paste the following url in a new tab: https://dashboard.heroku.com/new?template=replace_with_github_fork_url_here
4. deploy and you're all good to go!

**Comment by jatink007** [comment]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
I see this

**Comment by WSrujan** [comment]
I found the way out
shift/create new repo so we can deploy it simply using button(IF owner of this repo do it will be good)
heroku has flagged this repo check my method

**Comment by jatink007** [comment]
Ok I will. Check it out

**Comment by MaiSan0001** [comment]
> Update: seems the older version of the sniper works better than ever with heroku!

which version?

**Comment by InimicalPart** [comment]
> I found the way out
> shift/create new repo so we can deploy it simply using button(IF owner of this repo do it will be good)
> heroku has flagged this repo check my method

He probably won't, he has custom links designed, many stars and watchers, many forks, etc.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by InimicalPart** [comment]
> Vedza's sniper works fine on heroku, why on hell did they flag this one?

Well, both snipers are coded differently, and this one probably has code that Heroku flagged.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by InimicalPart** [comment]
> you can self deploy the code, it works fine

Maybe they just flagged the repo? 🤔

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by LavaRed** [comment]
Hey Guys i found a fix 😀

https://dashboard.heroku.com/new?template=https://github.com/thelinuxuser-choice/nitro-sniper

**Comment by WildKing2G** [comment]
> 
> 
> Hey Guys i found a fix 😀
> 
> https://dashboard.heroku.com/new?template=https://github.com/thelinuxuser-choice/nitro-sniper

working. thanks man ♥

**Comment by LavaRed** [comment]
> > Hey Guys i found a fix 😀
> > https://dashboard.heroku.com/new?template=https://github.com/thelinuxuser-choice/nitro-sniper
> 
> working. thanks man ♥

Your welcome bro!

**Comment by GiorgioBrux** [comment]
Quick heads up, if you use that link you are effectively running [this fork](https://github.com/thelinuxuser-choice/nitro-sniper), which is btw already behind 9 commits. Unless you trust the user in question, make your own fork as frosDfurret said.

**Comment by Cerexl** [comment]
I could actually get it to work before but not now...

**Comment by WildKing2G** [comment]
Same, doesn't work now. I'll try using "fork" but, I have the same error.

**Comment by Cerexl** [comment]
I actually deleted my working sniper to rrdo the process and get my webhook to work but now I can't get the sniper to work at all. Feels bad.
