### ISSUE TITLE
[Bug] I don't win giveaway yet bot still dms host

### ISSUE THREAD

**Issue by JonasBBX** [slow/nitro-sniper#15]
mhm still happening

_Originally posted by @JonasBBX in https://github.com/slow/nitro-sniper/issues/14#issuecomment-770316709_

**Comment by slow** [comment]
Does it say you won the giveaway in console?

Give me the total winners, giveaway name and how long it lasted.
If you have any other steps to reproduce it let me know.

**Comment by JonasBBX** [comment]
![image](https://user-images.githubusercontent.com/57160032/106373463-a247c980-6371-11eb-818b-51807cf13f74.png)

**Comment by JonasBBX** [comment]
like 1 winner and lasts about 10-30 mins (short ones)

**Comment by slow** [comment]
Are you 100% sure you didn't win?

**Comment by slow** [comment]
Also try to find those messages and show me them

**Comment by JonasBBX** [comment]
![image](https://user-images.githubusercontent.com/57160032/106373510-1edaa800-6372-11eb-98ae-5075b11f41cc.png)
![image](https://user-images.githubusercontent.com/57160032/106373527-47fb3880-6372-11eb-989b-da5dc534a250.png)

**Comment by slow** [comment]
🤔 thats really fucking weird

**Comment by slow** [comment]
i'll look into this

**Comment by slow** [comment]
for now, disable it

**Comment by JonasBBX** [comment]
sure tysm for helping man :)

**Comment by JonasBBX** [comment]
if you wanna message me via discord - NotJonas#8395
