### ISSUE TITLE
[Bug] payment method error

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#150]
Payment method error is due to epic game promotion which ended on 24 June and nitro code stays valid for 30 days so after that there will not be this error. This is my experience from previous discord promotion
Payment method error due to its nitro trial and for account which never got nitro

**Comment by InimicalPart** [comment]
Why are you making an issue?

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)
