### ISSUE TITLE
[Bug Report] Crashing on heroku

### ISSUE THREAD

**Issue by godpow** [slow/nitro-sniper#151]
![image](https://user-images.githubusercontent.com/17231911/124304596-eb26c880-db31-11eb-99fa-cf4e6062ff03.png)

**Comment by InimicalPart** [comment]
You need to take the screenshot a bit higher this doesn't tell us what the issue is

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by slow** [comment]
As said above, i'll be closing this issue as there doesn't seem to be a response from the author.
