### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fxyqq** [slow/nitro-sniper#154]
[2021-07-03 14:59:22] Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process...

here is the setting i hided my token you know

{
   tokens: {
      // Main Token
      main: "noWFQNSluG6RO",
      // Alt Tokens
      alts: [
         "rUuY_RCFLYqxDaY4L_G8"
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: "main",
   /*
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: 'default',
      // The status the logged in alts will have
      alts: 'default'
   },
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 5,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 24
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Message to DM the host
      dmMessage: 'Hey, i won the giveaway',
      // How long to wait to DM (in seconds)
      dmDelay: 15,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: false,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds)
         max: 20
      },
      members: {
         // The minimum member count the server should have
         min: 1500,
         // The maximum member count the server should have
         max: 50000
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours)
      cooldown: 6
   },
   webhook: {
      // URL to fire webhook to for notifications
      url: 'https://discord.com/api/webhooks/860890466161000478/Hxv7xvpeColIDbO4MuSqWB8RfL8phiDAKayB_UXAzu9Rv5FVnBMnC8916HWTRsLRN2Op',
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: true,
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: true,
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: true,
         // Fire webhook on giveaway win (true/false)
         giveawayWin: true,
         // Fire webhook on invite join (true/false)
         inviteJoin: false
      },
      mentionEveryone: {
         // Mention on invalid code (true/false)
         codeInvalid: false,
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false)
         codeSuccess: true,
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false)
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false
      }
   }
}

**Comment by fxyqq** [comment]
bro help me dont close it

**Comment by InimicalPart** [comment]
Try getting the latest default configuration. Make sure you didn't miss a ' somewhere, Make sure everything looks correct. `Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process...` only occurs when the JSON5 can't parse the settings file so there must be an error there somewhere

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by slow** [comment]
![image](https://user-images.githubusercontent.com/73202350/124359454-fe629280-dc1c-11eb-9201-fda689f6fcdf.png)
It's already valid, make sure you're on the latest version/commit.
Use this to validate: https://codebeautify.org/json5-validator

**Comment by fxyqq** [comment]
i did everything, its not working i think its because of this my token has like mfa._thentoken

**Comment by slow** [comment]
Show me your config with your tokens, replace only 1 of the characters from the tokens with something else so i can check whats up

**Comment by fxyqq** [comment]
and for heroku this happnes 
![Capture](https://user-images.githubusercontent.com/75327915/124359725-800aee00-dc26-11eb-9de5-24930eef49c4.PNG)

**Comment by fxyqq** [comment]
{
   tokens: {
      // Main Token
      main: 'mfa._b112BqAW4aXWESSDTJZOC2TLmRCqek-147vx0rgDP1CPNI9Uy9xrK_oCDEAA-M7T3J6S3DnoWFQNSluG6RO',
      // Alt Tokens
      alts: [
         'ODAzNzA2NTk0Mzg1NzIzNDgx.YOAhaA.r0VauF2rUuY_RCFLYqxDaY4L_G8',
         ''
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: 'main',
   /*
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: 'idle',
      // The status the logged in alts will have
      alts: 'default'
   },
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 5,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 24
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Message to DM the host
      dmMessage: 'Hey, i won the giveaway',
      // How long to wait to DM (in seconds)
      dmDelay: 15,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: false,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds)
         max: 20
      },
      members: {
         // The minimum member count the server should have
         min: 1500,
         // The maximum member count the server should have
         max: 50000
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours)
      cooldown: 6
   },
   webhook: {
      // URL to fire webhook to for notifications
      url: 'https://discord.com/api/webhooks/860890466161000478/Hxv7xvpeColIDbO4MuSqWB8RfL8phiDAKayB_UXAzu9Rv5FVnBMnC8916HWTRsLRN2Op',
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: true,
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: true,
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: true,
         // Fire webhook on giveaway win (true/false)
         giveawayWin: true,
         // Fire webhook on invite join (true/false)
         inviteJoin: false
      },
      mentionEveryone: {
         // Mention on invalid code (true/false)
         codeInvalid: false,
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false)
         codeSuccess: true,
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false)
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false
      }
   }
}

**Comment by slow** [comment]
do you have these before ur config
![FA745642-786F-4157-9DAF-3B43AE2BC8AF](https://user-images.githubusercontent.com/73202350/124359806-7087a700-dc1e-11eb-9c8e-2bcc483c4c68.jpeg)

**Comment by fxyqq** [comment]
> do you have these before ur config
> ![FA745642-786F-4157-9DAF-3B43AE2BC8AF](https://user-images.githubusercontent.com/73202350/124359806-7087a700-dc1e-11eb-9c8e-2bcc483c4c68.jpeg)

i sent my config here i will send it again

{
   tokens: {
      // Main Token
      main: 'mfa._b112BqAW4aXWESSDTJZOC2TLmRCqek-147vx0rgDP1CPNI9Uy9xrK_oCDEAA-M7T3J6S3DnoWFQNSluG6RO',
      // Alt Tokens
      alts: [
         'ODAzNzA2NTk0AMzg1NzIzNDgx.YOAhaA.r0VauF2rUuY_RCFLYqxDaY4L_G8',
         ''
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: 'main',
   /*
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: 'idle',
      // The status the logged in alts will have
      alts: 'default'
   },
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 5,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 24
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Message to DM the host
      dmMessage: 'Hey, i won the giveaway',
      // How long to wait to DM (in seconds)
      dmDelay: 15,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: false,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds)
         max: 20
      },
      members: {
         // The minimum member count the server should have
         min: 1500,
         // The maximum member count the server should have
         max: 50000
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours)
      cooldown: 6
   },
   webhook: {
      // URL to fire webhook to for notifications
      url: 'https://discord.com/api/webhooks/860890466161000478/Hxv7xvpeColIDbO4MuSqWB8RfL8phiDAKayB_UXAzu9Rv5FVnBMnC8916HWTRsLRN2Op',
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: true,
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: true,
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: true,
         // Fire webhook on giveaway win (true/false)
         giveawayWin: true,
         // Fire webhook on invite join (true/false)
         inviteJoin: false
      },
      mentionEveryone: {
         // Mention on invalid code (true/false)
         codeInvalid: false,
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false)
         codeSuccess: true,
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false)
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false
      }
   }
}

**Comment by slow** [comment]
I can't help you and i will not if you don't answer my questions.

**Comment by fxyqq** [comment]
> I can't help you and i will not if you don't answer my questions.

what is your question
