### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fxyqq** [slow/nitro-sniper#155]
ok so im sorry im being anoyying i need help dont close my issue, 
[2021-07-03 16:01:18] Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process...

{
   tokens: {
      // Main Token
      main: 'mfa._b112BqAW4aXWESSDTJZOC2TLmRCqek-147vx0rgDP1CPNI9Uy9xrK_oCDEAA-M7T3J6S3DnoWFQNSluG6RO',
      // Alt Tokens
      alts: [
         'ODAzNzA2NTk0Mzg1NzIzNDgx.YOAhaA.r0VauF2rUuY_RCFLYqxDaY4L_G8',
         ''
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: 'main',
   /*
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: 'idle',
      // The status the logged in alts will have
      alts: 'default'
   },
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 5,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 24
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Message to DM the host
      dmMessage: 'Hey, i won the giveaway',
      // How long to wait to DM (in seconds)
      dmDelay: 15,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: false,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds)
         max: 20
      },
      members: {
         // The minimum member count the server should have
         min: 1500,
         // The maximum member count the server should have
         max: 50000
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours)
      cooldown: 6
   },
   webhook: {
      // URL to fire webhook to for notifications
      url: 'https://discord.com/api/webhooks/860890466161000478/Hxv7xvpeColIDbO4MuSqWB8RfL8phiDAKayB_UXAzu9Rv5FVnBMnC8916HWTRsLRN2Op',
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: true,
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: true,
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: true,
         // Fire webhook on giveaway win (true/false)
         giveawayWin: true,
         // Fire webhook on invite join (true/false)
         inviteJoin: false
      },
      mentionEveryone: {
         // Mention on invalid code (true/false)
         codeInvalid: false,
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false)
         codeSuccess: true,
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false)
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false
      }
   }
}

this is my config

**Comment by slow** [comment]
Put this in your .env 
```js
settings="{
  tokens: {
    main: 'mfa._b112BqAW4aXWESSDTJZOC2TLmRCqek-147vx0rgDP1CPNI9Uy9xrK_oCDEAA-M7T3J6S3DnoWFQNSluG6RO',
    alts: [
      'ODAzNzA2NTk0Mzg1NzIzNDgx.YOAhaA.r0VauF2rUuY_RCFLYqxDaY4L_G8',
      '',
    ],
  },
  mode: 'main',
  status: {
    main: 'idle',
    alts: 'default',
  },
  nitro: {
    max: 5,
    cooldown: 24,
  },
  giveaway: {
    enabled: true,
    delay: 30,
    dm: true,
    dmMessage: 'Hey, i won the giveaway',
    dmDelay: 15,
    blacklistedWords: [
      'bot',
      'test',
      'ban',
    ],
    whitelistOnly: false,
    whitelistedWords: [
      'nitro',
    ],
    blacklistedServers: [
      '',
    ],
  },
  invite: {
    enabled: false,
    delay: {
      min: 10,
      max: 20,
    },
    members: {
      min: 1500,
      max: 50000,
    },
    max: 10,
    cooldown: 6,
  },
  webhook: {
    url: 'https://discord.com/api/webhooks/860890466161000478/Hxv7xvpeColIDbO4MuSqWB8RfL8phiDAKayB_UXAzu9Rv5FVnBMnC8916HWTRsLRN2Op',
    enabled: {
      codeInvalid: true,
      codeAlreadyRedeemed: true,
      codeSuccess: true,
      giveawayEntered: true,
      giveawayWin: true,
      inviteJoin: false,
    },
    mentionEveryone: {
      codeInvalid: false,
      codeAlreadyRedeemed: false,
      codeSuccess: true,
      giveawayEntered: false,
      giveawayWin: true,
      inviteJoin: false,
    },
  },
}"
```

**Comment by fxyqq** [comment]
tysm it worked
