### ISSUE TITLE
[Bug] Status "offline"

### ISSUE THREAD

**Issue by bonxz** [slow/nitro-sniper#166]
**Describe the bug**
When using the offline status, the account does not show as offline The Account is instead as mobile status marked.

**Comment by ShyLex** [comment]
Happens for me as well, hope it gets fixed

**Comment by kamikazeghost** [comment]
> **Describe the bug**
> When using the offline status, the account does not show as offline The Account is instead as mobile status marked.

are you sure you don't have discord mobile open?

**Comment by bonxz** [comment]
> 
> 
> > **Describe the bug**
> > When using the offline status, the account does not show as offline The Account is instead as mobile status marked.
> 
> are you sure you don't have discord mobile open?

I am one hundred percent sure.
how could i use mobile with over 10 accounts at the same time lol.

**Comment by slow** [comment]
This might be the websocket options, i'll have a look into this.
