### ISSUE TITLE
[Feature Request] The ability to add bot tokens

### ISSUE THREAD

**Issue by Motzumoto** [slow/nitro-sniper#171]
**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
I think it'd be awesome if we could add bot tokens to the sniper, for instance my friends bot is in 600 servers, and i almost guarantee those servers post nitro codes 

**Additional context**
None

**Comment by slow** [comment]
Have you checked if this already works? I believe it works, it's just the sharding manager that may need some tweaking for bots that are in 1k+ guilds.

**Comment by Motzumoto** [comment]
> Have you checked if this already works? I believe it works, it's just the sharding manager that may need some tweaking for bots that are in 1k+ guilds.

I have not checked if this works.. Let me do that

oh my god it does work

**Comment by slow** [comment]
It won't work, it will most likely just error in console.

**Comment by Motzumoto** [comment]
> It won't work, it will most likely just error in console.

it doesnt work, it logs in and shows the servers but nothing gets sniped

**Comment by nichevulcan20** [comment]
can the bot snipe codes to the main human account, if bot tokens are added in alt tokens?
