### ISSUE TITLE
Help on step 1 xD

### ISSUE THREAD

**Issue by SniperXKiller** [slow/nitro-sniper#173]
Hi, this is kind of embarrassing, but when I run "git clone https://github.com/slow/nitro-sniper nitro-sniper", it responds with "fatal: could not create work tree dir 'nitro-sniper': Permission denied". Can I have help?

**Comment by GiorgioBrux** [comment]
You don't have the write perms in the folder you are running git clone in, if you are on linux try sudo, if you are on windows check the security tab in the properties of the folder.

**Comment by SniperXKiller** [comment]
??? ( I don't do a lot of JS so I don't really understand )

**Comment by slow** [comment]
This is unrelated to the sniper, this is more of an issue with your environment. 

You also didn't follow the description of the "Bug" issue template which clearly states you should open a discussion instead of an issue if you need help with installation.
