### ISSUE TITLE
Not entering giveaways

### ISSUE THREAD

**Issue by MK007154** [slow/nitro-sniper#180]
### Discussed in https://github.com/slow/nitro-sniper/discussions/179

<div type='discussions-op-text'>

<sup>Originally posted by **MK007154** July 30, 2021</sup>
I've started the bot now and it's been on for about half an hour, however it's still not entering any giveaways. 
![image](https://user-images.githubusercontent.com/88198935/127668409-540294cf-741a-43bc-9a49-b11a29ccf16b.png)
![image](https://user-images.githubusercontent.com/88198935/127668441-a8407ec3-4963-4b2a-9bd2-102e7039a04f.png)
source code
giveaway: {
         },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 5,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Message to DM the host
      dmMessage: 'Hey, man i won the giveaway could i redeem prize',
      // How long to wait to DM (in seconds)
      dmDelay: 5,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: true,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro',
         'Nitro',
         'nitro classic',
         'Nitro Classic',
         'nitro Classic',
         'Nitro classic'</div>

**Comment by MK007154** [comment]
And btw what does this mean 
![image](https://user-images.githubusercontent.com/88198935/127669823-be7e7990-e8a6-4b68-8f93-c16ea1396796.png)

**Comment by slow** [comment]
This might be because of the new discord dates, i'll look into fixing this later.

**Comment by slow** [comment]
Please re-open the issue and use the bug report issue template.
