### ISSUE TITLE
[Bug] **Cannot deploy to heroku**

### ISSUE THREAD

**Issue by walkinginblood** [slow/nitro-sniper#186]
**Describe the bug**
Cannot deploy the sniper to heroku.

**To Reproduce**
1. Go to the installation page of the sniper github.
2. Click on deploy to heroku.
3. Scroll down to deploy app
4. Click deploy.

**Expected behavior**
I expected the sniper to be deployed to heroku.

**Screenshots**
![image](https://user-images.githubusercontent.com/77168060/128560788-8d541b7d-c47b-4889-b265-685d6572caa1.png)

**Comment by slow** [comment]
#149
