### ISSUE TITLE
[Bug] how to fix this error

### ISSUE THREAD

**Issue by SladeHazard** [slow/nitro-sniper#191]
C:\Users\Archer\Downloads\nitro-sniper-1.12.3\nitro-sniper-1.12.3>node .
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- C:\Users\Archer\Downloads\nitro-sniper-1.12.3\nitro-sniper-1.12.3\src\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\Archer\Downloads\nitro-sniper-1.12.3\nitro-sniper-1.12.3\src\index.js:1:27)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Archer\\Downloads\\nitro-sniper-1.12.3\\nitro-sniper-1.12.3\\src\\index.js'←[39m
  ]
}

**Comment by slow** [comment]
npm install then try again.

**Comment by SladeHazard** [comment]
I already tried that like 3 times even tried different machines & tried reinstalling.
