### ISSUE TITLE
[Feature Request] **CHANGE THIS TO A TITLE**

### ISSUE THREAD

**Issue by thizsam** [slow/nitro-sniper#193]
hey i have got a suggestion it would be great 
the giveaway sniper instead of reacting on basis of time could it react with number of reaction based like 
in .env we set to react at 5th place or 10th place 
then it should do so cuz 
giveaway bot doesnt pickup on time basis almost....implement it id u like it

**Comment by slow** [comment]
Please re-open the issue with the proper format.
