### ISSUE TITLE
[Bug] some node error...

### ISSUE THREAD

**Issue by tzt345** [slow/nitro-sniper#194]
**Describe the bug**
This
![Screenshot_2021-08-18-23-21-31-59](https://user-images.githubusercontent.com/83703996/129925649-0c66d2b8-2550-44d9-b575-888b323a85b1.png)

**To Reproduce**

**Expected behavior**
when I launched the nitro sniper it gave me a node warning

**Screenshots**
On the top

**Additional context**
NONE

**Comment by tzt345** [comment]
Is this fine?

**Comment by slow** [comment]
That seems like an error specific to your host, i can't reproduce this.
