### ISSUE TITLE
[Feature Request] **fix heroku**

### ISSUE THREAD

**Issue by Barry-16** [slow/nitro-sniper#196]
**heroku blocked it [...]

**fix it**
I would like to be able to actually use it

**Additional context**
I get the following error when attempting to deploy the app

Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by noobdeveloper-lang** [comment]
Just go to setting and rename your repo to any name  except the original one

**Comment by slow** [comment]
Fixed in af13ccf035414dcce5cc3f18f120d4734b782013
