### ISSUE TITLE
Heroku Account Suspended

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#197]
![suspended](https://user-images.githubusercontent.com/49693115/130314210-c4549aa4-1894-4dfa-9bb7-3a204500c3bf.png)
time to create one more (fork one got banned)

**Comment by thizsam** [comment]
deploying bots of pinging on heroku is against tos of thier policy

**Comment by WSrujan** [comment]
i know this program is illegal but hosting normal discord bot also illegal on heroku?

**Comment by slow** [comment]
fixed
