### ISSUE TITLE
[Bug] *Heroku Private Repository Error**

### ISSUE THREAD

**Issue by thefrozen-coder** [slow/nitro-sniper#198]
**Describe the bug**

**To Reproduce**
1. Go to 'https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fheroku-hate-club%2FKA7myEybvKGiL%2Ftree%2Fmain'
2. Sorry but I'm not sure either this is Github's Error or Heroku's error but can you please tell how to fix this?

![image](https://user-images.githubusercontent.com/84008208/130351708-47675567-ea8d-4b1e-80eb-aa9a5951b26f.png)

**Comment by slow** [comment]
![image](https://media.wtf/68414189)
It seems that you were checking out a certain tag which had an outdated link in the readme.

Please make sure you always have the "main" branch selected to ensure the latest link is provided as the link changes hourly to avoid heroku bans/suspensions.
