### ISSUE TITLE
custom giveaway jioner

### ISSUE THREAD

**Issue by thizsam** [slow/nitro-sniper#199]
Custom giveaway joiner:
custombots | Show & manage bots for giveaway joiner
    custombot <botid> | Manage giveaway bot
        cbemoji <botid> <emoji> | Emoji to react
        cbtext <botid> <text> | Plain text to trigger
        cbtitle <botid> <text> | Embed title text to trigger
        cbdescription <botid> <text> | Embed description text to trigger
        cbauthor <botid> <text> | Embed author text to trigger
addbot <botid> | Add custom giveaway bot
rmbot <botid> | Remove custom giveaway bot

**Comment by slow** [comment]
Good suggestion, however i'll need you to re-open the issue and use the issue template.
