### ISSUE TITLE
Big Difference using repl.it and heroku

### ISSUE THREAD

**Issue by MaiSan0010** [slow/nitro-sniper#213]
on repl.it almost everything get sniped the time taken it's <100ms instead for heroku >100ms  i wonder if it's okey?
![image](https://user-images.githubusercontent.com/89659009/132171531-23a53fcd-e697-4485-ae58-a216fe03934b.png)
![image](https://user-images.githubusercontent.com/89659009/132171536-1ea3693a-dbfb-4631-ba41-70e0095e1fcb.png)
![image](https://user-images.githubusercontent.com/89659009/132171548-ad0f65e0-2b77-44f7-92f7-890a1c5abf0f.png)
![image](https://user-images.githubusercontent.com/89659009/132171555-8fd4ac89-57ac-48ff-8f46-03155da5c5d3.png)
![image](https://user-images.githubusercontent.com/89659009/132171565-7d6fb89c-a4b3-45ad-895a-f33151b02108.png)
![image](https://user-images.githubusercontent.com/89659009/132171568-9ac3f04c-2d3b-485b-a7f9-7190c7050840.png)

**Comment by slow** [comment]
I don't know what to tell you, heroku blacklists any repo with even a little bit of code from this one. I recommend either running this on a VPS or something with high bandwidth thats located near the USA.

Apologies.

**Comment by MaiSan0010** [comment]
okey thanks for the fast reply!

**Comment by MaiSan9999** [comment]
> I don't know what to tell you, heroku blacklists any repo with even a little bit of code from this one. I recommend either running this on a VPS or something with high bandwidth thats located near the USA.
> 
> Apologies.

Anyway i noticed im still able run the old version of nitro sniper on heroku and i wonder if 90-60ms are good

**Comment by Saytoo** [comment]
> > I don't know what to tell you, heroku blacklists any repo with even a little bit of code from this one. I recommend either running this on a VPS or something with high bandwidth thats located near the USA.
> > Apologies.
> 
> Anyway i noticed im still able run the old version of nitro sniper on heroku and i wonder if 90-60ms are good

do you still have the old version and does it still works?
