### ISSUE TITLE
[Bug] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Mahas1** [slow/nitro-sniper#216]
**Describe the bug**
```
(node:766) UnhandledPromiseRejectionWarning: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1561:19)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```
this is noticed while the program is running.

**To Reproduce**
1. Run the program
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/82939599/132291019-583b18f2-ee00-40e3-99af-c01b9ce31c41.png)

**Comment by EnzoDeg40** [comment]
My config file was wrong, try to verify you config file

**Comment by ShamailNasir** [comment]
I have the same problem and can't seem to fix it, if you find any solution please let me know

**Comment by Mahas1** [comment]
> I have the same problem and can't seem to fix it, if you find any solution please let me know

I think it was as @EnzoDeg40 said, I remade the `settings variable, and i havent noticed anything since

**Comment by AryaAnish121** [comment]
You guys use github just for nitro-sniper?
