### ISSUE TITLE
[MESSAGE] **DISCORD SERVER GONE!**

### ISSUE THREAD

**Issue by dotpeak** [slow/nitro-sniper#217]
**Additional context**
The discord server is gone please make a new server.
:0

**Comment by MaiSan0010** [comment]
they have a discord server?

**Comment by dotpeak** [comment]
> they have a discord server?

yes but it might of been deleted since a few people I know where in the server are no longer in it including me

**Comment by Ikhari** [comment]
hey peak i'm Ikhari. it surprised me in the morning, when i wanted to check discord server and it was gone..., anyone know why?

**Comment by slow** [comment]
it's been terminated.
