### ISSUE TITLE
Question Will replit stay online 24/7?

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#223]
when i used too code on replit it went offline after 30 min of inactivity (not talking about sniper)
will sniper react differently?

**Comment by gitiliya** [comment]
no, i recommend running it on your local device

**Comment by raVenoxis** [comment]
you can run on replit 24/7 with uptimerobot

**Comment by slow** [comment]
Use uptime robot.

**Comment by WSrujan** [comment]
Now pinger is removed now what can we do make it 24/7
