### ISSUE TITLE
[Feature Request] Possibility for the Invite sniper to work with Vanity url

### ISSUE THREAD

**Issue by MrD4rio** [slow/nitro-sniper#230]
**Is your feature request related to a problem? Please describe.**
After making some tests, I've noticed that the Invite sniper does not join servers which link is a vanity url (custom invite links basically), if I give the account a list of servers where there's both normal invite links (with random numbers/letters) and vanity urls (ex. discord.gg/boobs) it will join only the normal invite links.

**Describe the solution you'd like**
Make the Invite sniper recognize vanity urls as invites too being able to join them

Thanks for your time :)

**Comment by slow** [comment]
Keep in mind the minimum and maximum member count settings decide if the sniper joins too, it seems that it works for me but it wont work with invite links that are under 2 characters, I'll push a fix soon for it not grabbing short invite links.
