### ISSUE TITLE
[Bug] Any ideas why I get this error, after 5 mins Nitro Sniper is running it gives me this.

### ISSUE THREAD

**Issue by CloudyX2021** [slow/nitro-sniper#237]
(node:1824) UnhandledPromiseRejectionWarning: Error: write EPROTO 139635653433152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1824) UnhandledPromiseRejectionWarning: Error: write EPROTO 139635653433152:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
(node:1824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by Tunglatrum** [comment]
i also got the same issue!Pls fix this

**Comment by paaaazuu** [comment]
Same issue here.

**Comment by ultra589** [comment]
Same issue here man.

**Comment by slow** [comment]
I've pushed an update, let me know if the issue still occurs.

**Comment by paaaazuu** [comment]
Works fine for me. Thanks!

**Comment by WSrujan** [comment]
Now pinger is removed now what can we do make it 24/7

**Comment by bettydreemurr** [comment]
@WSrujan what you can do to fix this is go to the /src/lib/Dashboard.js file

![image](https://user-images.githubusercontent.com/46537034/133652031-a92636a5-2574-42b9-9788-b5584b4931c2.png)

and then copy and paste what is just below my message, (it's just the old code to use to display the site on replit)

```js
const express = require('express');
const phin = require('phin');

module.exports = class Dashboard {
  constructor() {
    this.server = null;
    this.port = null;
    this.listener = null;

    const { REPL_SLUG, REPL_OWNER } = process.env;

    if (REPL_SLUG && REPL_OWNER) {
      this.start();
    }
  }

  keepAlive() {
    const { REPL_SLUG, REPL_OWNER } = process.env;
    if (!REPL_OWNER || !REPL_SLUG) return;

    const url = `https://${REPL_SLUG}.${REPL_OWNER}.repl.co/`;
    setInterval(async () => {
      const res = await phin({ url, method: 'GET' });
      if (res.statusCode == 200) logger.debug(`Pinged URL ${url}`);
    }, 1000);

    // this.start();
  }

  start() {
    this.server = express();
    this.attachListeners();
    this.keepAlive();

    // To be continued...
  }

  attachListeners() {
    this.listener = this.server.listen(process.env.PORT || 3000, () => {
      this.port = this.listener.address().port;
      logger.debug(`Pinger listening on ${this.port}.`);
    });

    this.server.all('/', (req, res) => {
      res.send('Your bot is alive!');
    });
  }
};
```

**Comment by WSrujan** [comment]
Thank You so much

**Comment by slow** [comment]
Do not expect any support with this - this is the code that causes the error you had when you opened this issue.
