### ISSUE TITLE
[Bug] You Are Being Rate Limited

### ISSUE THREAD

**Issue by CandyBotDJS** [slow/nitro-sniper#242]
**Describe the bug**
```
Unknown Response | You are being rate limited. | Code: 5vg2S3gabgqmucBw7qfqFTCT | S͓̽p͓̽i͓̽d͓̽e͓̽r͓̽A͓̽r͓̽m͓̽y͓̽!! • Nitro • Giveaway • > #💬-chคҭ | pepsi#0423 | 38ms
```

**To Reproduce**
1. Run Bot
2. Send A Random Code (Working One & Can Be Already Redeemed) To The Alt
3. See error

**Expected behavior**
Like Gives Its Already Claimed Or Smth

**Screenshots**
![image](https://user-images.githubusercontent.com/90443263/133633002-d839d9d6-f786-4e04-8e7b-ab3a0da0561d.png)

**Additional context**
Im Running The Bot On Replit With A Main Account And No Alts (Configured Correctly)

**Comment by slow** [comment]
This is most likely because codes have been spammed, how many codes are above that one?

**Comment by b1ank3r** [comment]
do this sniper redeem the invalids one on the alt acc or main acc, doing it on alt would be better rite

**Comment by slow** [comment]
This has been handled in a968c571bbfbae29a1d9407f0bf2c5afb9c47965, it will not stop the error from happening but it will wait until your ratelimit is over and continue sniping after that.

Functionality of the bot is untouched as you wouldn't be able to snipe other codes while ratelimited so waiting the ratelimit doesn't cause any harm.
