### ISSUE TITLE
Invalid settings

### ISSUE THREAD

**Issue by M0nK100** [slow/nitro-sniper#247]
Invalid settings, please use https://jsonformatter.org/json5-validator to validate your settings. Exiting process...
I checked the json files, they are perfectly fine. Idk what is the problem. (On local PC)

**Comment by slow** [comment]
read.

**Comment by CrazyCSIW6** [comment]
JSON5 Validator came back with "VALID JSON5", and I still have this problem.

**Comment by Aviiiiiiiiiiiiii** [comment]
bro i have the same issue plz help me i am a new to coding
