### ISSUE TITLE
[Bug] ** Code is not even starting it only shows invalid settings **

### ISSUE THREAD

**Issue by Aviiiiiiiiiiiiii** [slow/nitro-sniper#250]
**Describe the bug**
Invalid settings, please use https://jsonformatter.org/json5-validator to validate your settings. Exiting process...
exit status 255

![image](https://user-images.githubusercontent.com/91025127/133954080-3cdeb235-f386-4729-8f1e-987c1b0d242a.png)

**Comment by InimicalPart** [comment]
Please check https://github.com/slow/nitro-sniper#default-configuration, paste it into your ".env" file, don't forget to change the tokens.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)
