### ISSUE TITLE
Doesn't work for some reason.

### ISSUE THREAD

**Issue by rckstarw** [slow/nitro-sniper#251]
![image](https://user-images.githubusercontent.com/91045691/133960773-f9d97837-0575-4129-a5d5-08098c8e125e.png)

**Comment by 7uh** [comment]
have you added your token into the code?

**Comment by rckstarw** [comment]
Actually I didn't @7uh

**Comment by rckstarw** [comment]
Where do I add it? @7uh

**Comment by 7uh** [comment]
watch this video and copy what he does https://www.youtube.com/watch?v=D64WcTLpzes&t=36s

**Comment by rckstarw** [comment]
Alr thx

**Comment by rckstarw** [comment]
![image](https://user-images.githubusercontent.com/91045691/133962034-d4d796ed-9587-4ce9-a012-3d709b969ac2.png)
@7uh it shows this now?

**Comment by slow** [comment]
This isn't a reading class.
