### ISSUE TITLE
[Bug] Repl.it stop running

### ISSUE THREAD

**Issue by NelsonH75** [slow/nitro-sniper#254]
**Describe the bug**
When using repl.it it will sometimes stop and have to rerun repl.it

**To Reproduce**
Just try for like 10-24 hours or so.

**Screenshots**

**Additional context**

**Comment by InimicalPart** [comment]
Please explain this bug in more detail and please attach some screenshots. Right now this sounds like a repl.it problem.

> If you liked my response, let me know by reacting with a heart ❤️ Have a nice day, fella! :)

**Comment by bettydreemurr** [comment]
I use replit and uptimerobot.com so that the program does not shut down

![Screenshot_2021-09-21-07-30-11-27_a69665f6e53cb92f02c869f8651c0d02.jpg](https://user-images.githubusercontent.com/46537034/134116361-e84b362f-7806-4ec4-9cc3-cbcba706b4a7.jpg)

**Comment by slow** [comment]
Please follow the guide in the README of how to setup uptimerobot. This will make sure your sniper runs 24/7 even when you aren't active on your computer!
