### ISSUE TITLE
Not Working pls help :/

### ISSUE THREAD

**Issue by MQCraft** [slow/nitro-sniper#255]
i did everything but its shows 
[2021-09-21 05:03:31] Main token does not have a billing source, some codes will not be sniped.
[2021-09-21 05:03:31] Logged in with 1 account and 19 servers.

and does nothing pls help me

**Comment by RXNationCoding** [comment]
Hmmm

**Comment by slow** [comment]
this must be a joke

**Comment by MQCraft** [comment]
no bruh pls help me

**Comment by nxmedrxgx** [comment]
i have the same problem 

https://imgur.com/6Q0N3lq

**Comment by slow** [comment]
That means it works.

**Comment by MQCraft** [comment]
bro i dint work i waited for 48 hours

**Comment by slow** [comment]
What don't you get from the word "Sniper".

People have to drop codes, it's not about how long you wait.
