### ISSUE TITLE
[Bug] Unexpected Token '.'

### ISSUE THREAD

**Issue by xyn-n** [slow/nitro-sniper#26]
Apologies if I'm making a mistake here. I'm fairly new to this whole thing.

When attempting to use `node .` I get an error message in CMD telling me there's a synax error. The exact error is:

![Error](https://images2.imgbox.com/57/5e/cQqwRHoU_o.png)

I haven't a clue how to fix it, I'd really appreciate some help.

**Comment by slow** [comment]
You need to use node 14 or above. Redownload a later version of node.
