### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SimplePog** [slow/nitro-sniper#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
https://i.imgur.com/09g49fo.png
While using default config it don't work

**Comment by slow** [comment]
Can i see your config? Replace tokens with `x`

**Comment by SimplePog** [comment]
{
   "tokens": {
      "main": "x", // Main Token
      "alts": [
         "notusingthis" // Alt Tokens
      ],
   },
   "mode": "main", // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   "nitro": {
      "max": 12, // The amount of nitros needed to be sniped for the cooldown to activate
      "cooldown": 1 // Cooldown to activate after max nitro has been hit (in hours)
   },
   "giveaway": {
      "enabled": true, // Wether or not to activate the giveaway sniper (true/false)
      "delay": 30, // Delay to react to the giveaway (in seconds)
      "dm": true, // DM the hoster on giveaway win (true/false)
      "dmMessage": "Hey, i won the giveaway. Could i redeem my prize?", // Message to DM the host
      "dmDelay": 25, // How long to wait to DM (in seconds)
      "blacklistedWords": [ // Blacklisted words for giveaway prizes
         "bot",
         "test",
         "ban"
      ],
      "whitelistOnly": false, // Only react to whitelisted giveaway prizes (true/false)
      "whitelistedWords": [ // Whitelisted words for giveaway prizes
         "nitro"
      ],
      "blacklistedServers": [ // Blacklisted Server IDs to not snipe giveaways on
         ""
      ]
   },
   "invite": {
      "enabled": true, // Wether or not to activate the invite sniper (true/false)
      "delay": {
         "min": 10, // Minimum delay to join the server (in seconds)
         "max": 20 // Maximum delay to join the server (in seconds)
      },
      "members": {
         "min": 1500, // The minimum member count the server should have
         "max": 50000 // The maximum member count the server should have
      },
      "max": 10, // The amount of joined invites needed for the cooldown to activate
      "cooldown": 6 // Cooldown to activate after max joined invites has been hit (in hours)
   },
   "webhook": { 
      "url": "https://discord.com/api/webhooks/810402577124425738/0PLFMgCL8-LGTKkce3PwFqmEOrCtKjmnYLUKPfb9Hx-s6cvn24elx8luCbZ6qOT0rhBO", // URL to fire webhook to for notifications
      "enabled": {
         "codeInvalid": true, // Fire webhook on invalid code (true/false)
         "codeAlreadyRedeemed": true, // Fire webhook on already redeemed code (true/false)
         "codeSuccess": true, // Fire webhook on sniped code (true/false)
         "giveawayEntered": true, // Fire webhook on giveaway enter (true/false)
         "giveawayWin": true, // Fire webhook on giveaway win (true/false)
         "inviteJoin": true // Fire webhook on invite join (true/false)
      }, 
      "mentionEveryone": { 
         "codeInvalid": false, // Mention on invalid code (true/false)
         "codeAlreadyRedeemed": false, // Mention on already redeemed code (true/false)
         "codeSuccess": true, // Mention on sniped code (true/false)
         "giveawayEntered": true, // Mention on giveaway enter (true/false)
         "giveawayWin": true, // Mention on giveaway win (true/false)
         "inviteJoin": false // Mention on invite join (true/false)
      }
   }
}

**Comment by SimplePog** [comment]
{
   "tokens": {
      "main": "x", // Main Token
      "alts": [
         "notusingthis" // Alt Tokens
      ],
   },
   "mode": "main", // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   "nitro": {
      "max": 12, // The amount of nitros needed to be sniped for the cooldown to activate
      "cooldown": 1 // Cooldown to activate after max nitro has been hit (in hours)
   },
   "giveaway": {
      "enabled": true, // Wether or not to activate the giveaway sniper (true/false)
      "delay": 30, // Delay to react to the giveaway (in seconds)
      "dm": true, // DM the hoster on giveaway win (true/false)
      "dmMessage": "Hey, i won the giveaway. Could i redeem my prize?", // Message to DM the host
      "dmDelay": 25, // How long to wait to DM (in seconds)
      "blacklistedWords": [ // Blacklisted words for giveaway prizes
         "bot",
         "test",
         "ban"
      ],
      "whitelistOnly": false, // Only react to whitelisted giveaway prizes (true/false)
      "whitelistedWords": [ // Whitelisted words for giveaway prizes
         "nitro"
      ],
      "blacklistedServers": [ // Blacklisted Server IDs to not snipe giveaways on
         ""
      ]
   },
   "invite": {
      "enabled": true, // Wether or not to activate the invite sniper (true/false)
      "delay": {
         "min": 10, // Minimum delay to join the server (in seconds)
         "max": 20 // Maximum delay to join the server (in seconds)
      },
      "members": {
         "min": 1500, // The minimum member count the server should have
         "max": 50000 // The maximum member count the server should have
      },
      "max": 10, // The amount of joined invites needed for the cooldown to activate
      "cooldown": 6 // Cooldown to activate after max joined invites has been hit (in hours)
   },
   "webhook": { 
      "url": "api", // URL to fire webhook to for notifications
      "enabled": {
         "codeInvalid": true, // Fire webhook on invalid code (true/false)
         "codeAlreadyRedeemed": true, // Fire webhook on already redeemed code (true/false)
         "codeSuccess": true, // Fire webhook on sniped code (true/false)
         "giveawayEntered": true, // Fire webhook on giveaway enter (true/false)
         "giveawayWin": true, // Fire webhook on giveaway win (true/false)
         "inviteJoin": true // Fire webhook on invite join (true/false)
      }, 
      "mentionEveryone": { 
         "codeInvalid": false, // Mention on invalid code (true/false)
         "codeAlreadyRedeemed": false, // Mention on already redeemed code (true/false)
         "codeSuccess": true, // Mention on sniped code (true/false)
         "giveawayEntered": true, // Mention on giveaway enter (true/false)
         "giveawayWin": true, // Mention on giveaway win (true/false)
         "inviteJoin": false // Mention on invite join (true/false)
      }
   }
}

**Comment by slow** [comment]
Why do you have the comments? Don't change the default configuration that you're provided with on heroku or in the .env, the one in the readme is for reference and contains comments, which will break the config.
