### ISSUE TITLE
[Bug] Time Taken (ms) is too much

### ISSUE THREAD

**Issue by AnshulKale08** [slow/nitro-sniper#282]
### Describe the bug

As you might know me , you helped me yersterday.
The sniper is working fine except that it has a very big "time taken" time. Sometimes I get 333 ms , 435 , 1023. 
These are extremely big time considering that there would be other snipers in the server. 
Also as I mentioned before in my previous issue which is currently pinned, My nitro sniper on heroku gives pings less than 100 and very rarely above 100.

So is there any way to reduce the time taken to below 100ms. 
Also my bandwidth is considerably good and if it takes short time on heroku why does it take more on replit.

Also if you are guessing that why I am not using the heroku one , well I have borrowed it for some time from my friend and I need my own sniper so I am doing all this.

### To Reproduce

Setup the whole nitro sniper and then check the logs for the time taken.

### Expected behavior

Should have given less time for the time taken which is below 100ms

### Please provide your snipers settings.

```javascript
Doesnt matter in this case , It works anyway.
```

### What platform are you seeing the problem on?

Repl.it

### Relevant log output if applicable.

```text
Invalid Code
Time Taken
1028ms
Code
StE6ytEtbu6cYPke
```

**Comment by slow** [comment]
Not a bug.
