### ISSUE TITLE
[Bug] When you deploy the sniper to heroku your account gets suspended

### ISSUE THREAD

**Issue by ibndiaye** [slow/nitro-sniper#29]
Hello, I recently found an issue when you deploy the sniper you get suspended from Heroku.

After a few minutes you get an authentication error, and you have to sign in again and when you attempt to log in your account  you can't sign in.

When you check your email, and you'll see that your account was suspended. 
![image](https://user-images.githubusercontent.com/63436162/108013255-97e12d00-700b-11eb-9945-23058c24f3b3.png)

I don't mind, was just a throwaway account.

**Comment by IzukuMidoriyaPHP** [comment]
same just now for me

**Comment by slow** [comment]
Follow the issue template. It's there for a reason.

I'm aware of those and Im actively trying to put my finger on the cause. No ETA.

**Comment by Tropixi** [comment]
Same issue for me

**Comment by IWolfZ** [comment]
same issue

**Comment by IWolfZ** [comment]
Im hoping it gets fixed soon because I have bad ping, and its 24/7

**Comment by csnbd** [comment]
pls fix this

**Comment by Tropixi** [comment]
Well he's been trying multiple times to fix it, there isn't really a way to go around it.

**Comment by slow** [comment]
As @Tropixi said, i've tried a bunch of fixes. Nothing seemed to fix it.
I might have to resort to a github action that will obfuscate the code and deploy it to another branch if any commit is made to the main branch.

Thanks @GiorgioBrux for the idea.

**Comment by x-Tera-x** [comment]
> As @Tropixi said, i've tried a bunch of fixes. Nothing seemed to fix it.
> I might have to resort to a github action that will obfuscate the code and deploy it to another branch if any commit is made to the main branch.
> 
> Thanks to @GiorgioBrux for the idea.

how to contact do you have a discord server or username that I can add ?

**Comment by slow** [comment]
Fix incoming.

**Comment by JonasBBX** [comment]
>  This issue has been resolved in version 1.7.2 
> 
> The release is available on [GitHub release](https://github.com/slow/nitro-sniper/releases/tag/v1.7.2)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot

aye you actually fixed it nice and btw rip my discord again lmao
