### ISSUE TITLE
[Feature Request]  Include more giveaway bots sniper

### ISSUE THREAD

**Issue by proable** [slow/nitro-sniper#298]
### Is your feature request related to a problem?

giveaway bot only works for standard giveaway bot.

### Describe the solution you'd like

include invite tracker giveaway and giveaway boat.

### How will this be beneficial to the sniper

able to participate in more giveaways and not just limited to the standard giveaway bot giveaways.

### Please provide an example of usage of this feature

giveaway snipers participate in other giveaway bots giveaways as well.

**Comment by slow** [comment]
dupe of #152
