### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by zin9747** [slow/nitro-sniper#299]
### Describe the bug

main.sh: line 1: wget: command not found
thats what i get when i run

### To Reproduce

above

### Expected behavior

above

### Please provide your snipers settings.

```javascript
above
```

### Relevant log output if applicable.

```text
above
```

**Comment by Craftzman7** [comment]
Install wget. Not that hard. Debian based distros: `sudo apt install wget -y` CentOS: `sudo yum install wget`
