### ISSUE TITLE
[Feature Request] invite injector

### ISSUE THREAD

**Issue by danny27404** [slow/nitro-sniper#305]
### Is your feature request related to a problem?

A custom way to add invite codes to all the alts when invite timers on cooldown. e.g i have all 300 alts in my own private server so i can keep a eye on them been banned..... they all snipe however would be good if i added the invite link to my server and say a code before hand like Override was picked up by the bot and added that link.

### Describe the solution you'd like

Allow additional server invite injections

### How will this be beneficial to the sniper

easier managment of alts

### Please provide an example of usage of this feature

servers with short join windows and private codes

**Comment by danny27404** [comment]
edit here just a whitelist server for invite only would be good like you have whitelist for giveaways

**Comment by slow** [comment]
Just… send another message with an invite?

**Comment by killmak** [comment]
If you are still looking for a workaround it is pretty simple to manually add a single server that it will only grab invites from.  Open invite.js in a text editor.  Find the line - async handleInvite(msg) {
Under this line add two new lines of code exactly as written (changing the number to your private discords server ID)
   if (msg?.channel.type !== 'text') return;
   if (msg.guild.id != '000000000') return;
The first line will filter out non text channels which can cause an issue with fetching msg.guild.id
The second line checks if the message comes from your private server before continuing.

**Comment by Motzumoto** [comment]
good god 300 fucking alts? Jesus fuck.
