### ISSUE TITLE
[Bug] Suggestion/request/fix dm message

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#313]
### Describe the bug

Dm message is customize right?
it doesn't change when i change it .env (secret) so i checked code found it in constant file and changed it
make it so that it replace constant if there is change in .env

### To Reproduce

Sniper files changing

### Expected behavior

change of message

### Please provide your snipers settings.

```javascript
same as default with more blacklist and different dm message
```

**Comment by slow** [comment]
The sniper needs to be restarted before anything in the env changes.

**Comment by WSrujan** [comment]
I did restart but didn't reflect it
you can check it yourself
