### ISSUE TITLE
[Bug] Duplicate of #313 cause you closed it 

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#314]
### Describe the bug

changed dm message in .env (secret) and RESTARTED the sniper. tested giveaway and it didnt change the message.
so i looked in constant and found. When i changed dm message there it changed

### To Reproduce

1)change dm message in .env
2) restart the sniper

### Expected behavior

Change of message

### Please provide your snipers settings.

```javascript
default
just dm message changed
```

### What platform are you seeing the problem on?

Repl.it

**Comment by WSrujan** [comment]
You can test it out yourself

**Comment by slow** [comment]
noone has this issue
