### ISSUE TITLE
[Feature Request] smart nitro sniper

### ISSUE THREAD

**Issue by AvaneeshG** [slow/nitro-sniper#318]
### Is your feature request related to a problem?

meh i just would like the wiki to be updated 

### Describe the solution you'd like

```
blacklistedWords: [
         'bot',
         'auto',
         'van',
         'test',
         'ban',
         'start',
         'extra',
         'end',
         'kick',
         'nitro sniper'
      ],
```

### How will this be beneficial to the sniper

bascilly bypass most of the things that could possibly catch a nitro sniper

### Please provide an example of usage of this feature

new giveaway called "nitro react = van" (ps. i got banned for this)
new giveaway called "react = kicked"
new giveaway called "nitro sniper" (p.s almost got caught)

extra/end/start gws are harmless unless they have a rule that will autoban you if you react to these but i suggest adding them because you dont want pings just beacuse you won a "extra" gw

**Comment by WSrujan** [comment]
blacklist is already there check .env / secret
