### ISSUE TITLE
Problem when clicked run on repl.it

### ISSUE THREAD

**Issue by NotAtic** [slow/nitro-sniper#323]
### Describe the bug

bash main.sh
main.sh: line 1: wget: command not found

I tried like 10 times yesterday and today, is there a way to fix this?
been trying forever

### To Reproduce

I don't know

### Expected behavior

It should have ran and worked

### Please provide your snipers settings.

```javascript
what is this?
```

### What platform are you seeing the problem on?

Repl.it

### Relevant log output if applicable.

```text
bash main.sh
main.sh: line 1: wget: command not found
```

**Comment by AvaneeshG** [comment]
Read wiki probably

**Comment by slow** [comment]
Follow the wiki properly and make it a “bash” app.

**Comment by maanya125** [comment]
I made a solution for it, I had same issues , I fixed and made a repo , but no one saw it lol ,

here it is : https://github.com/maanya125/sniper-deploy

u can deploy in 1 click
