### ISSUE TITLE
[Bug] main.sh: line 1: wget: command not found

### ISSUE THREAD

**Issue by Sxtqq** [slow/nitro-sniper#324]
### Describe the bug

when i run the sniper on replit i just get this error "main.sh: line 1: wget: command not found"
i have followed the wiki word for word

### To Reproduce

run the sniper on replit

### Expected behavior

it should have ran the sniper without problems

### Please provide your snipers settings.

```javascript
{
   tokens: {
      // Main Token (ex: Nz...)
      main: '...',
      // Alt Tokens (ex: Nz...)
      alts: [
         '',
      ],
   },
   // The mode to run the sniper in. Options: main (only main account), alts (only alts), both
   mode: 'both',
   /*
      The status the accounts should be on.
      Options: online, dnd, idle, offline, default
      default means the status will not be modified.
   */
   status: {
      // The status the main account will have IF it's logged in
      main: 'default',
      // The status the logged in alts will have
      alts: 'default'
   },
   nitro: {
      // The amount of nitros needed to be sniped for the cooldown to activate
      max: 2,
      // Cooldown to activate after max nitro has been hit (in hours)
      cooldown: 24,
      dm: {
         /*
          * How long to wait before attempting to claim the nitro in DMs (in seconds)
          * This is to avoid suspicion when winning giveaways by slowing down the sniper from instantly sniping it.
          */
         delay: 10
      }
   },
   giveaway: {
      // Wether or not to activate the giveaway sniper (true/false)
      enabled: true,
      // Delay to react to the giveaway (in seconds)
      delay: 30,
      // DM the hoster on giveaway win (true/false)
      dm: true,
      // Messages to DM the host
      dmMessages: [
         'yo',
         'can i claim my prize i won it in the giveaway'
      ],
      // How long to wait to DM (in seconds)
      dmDelay: 25,
      // How long to wait between messages (in seconds)
      messageDelay: 2,
      // Blacklisted words for giveaway prizes
      blacklistedWords: [
         'bot',
         'test',
         'ban'
      ],
      // Only react to whitelisted giveaway prizes (true/false)
      whitelistOnly: false,
      // Whitelisted words for giveaway prizes
      whitelistedWords: [
         'nitro'
      ],
      // Blacklisted Server IDs to not snipe giveaways on
      blacklistedServers: [
         ''
      ],
      // Only snipe giveaways on whitelisted servers (true/false)
      whitelistServersOnly: false,
      whitelistedServers: [
        ''
      ]
   },
   invite: {
      // Wether or not to activate the invite sniper (true/false)
      enabled: false,
      delay: {
         // Minimum delay to join the server (in seconds)
         min: 10,
         // Maximum delay to join the server (in seconds)
         max: 20
      },
      members: {
         // The minimum member count the server should have
         min: 1500,
         // The maximum member count the server should have
         max: 50000
      },
      // The amount of joined invites needed for the cooldown to activate
      max: 10,
      // Cooldown to activate after max joined invites has been hit (in hours)
      cooldown: 6,
      // Whether to accept an invite on any other alt/account (depends on "mode") if the current alt has max servers (true/false)
      queue: true,
      // Whether to allow the main token to snipe invites ONLY if sniper mode is set to "both" (true/false)
      onlyAlts: true
   },
   webhook: {
      // URL to fire webhook to for notifications (ex: https://discord.com/api/webhooks/.../...)
      url: '...',
      enabled: {
         // Fire webhook on invalid code (true/false)
         codeInvalid: false,
         // Fire webhook on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Fire webhook on sniped code (true/false)
         codeSuccess: true,
         // Fire webhook on giveaway enter (true/false)
         giveawayEntered: true,
         // Fire webhook on giveaway win (true/false)
         giveawayWin: true,
         // Fire webhook on invite join (true/false)
         inviteJoin: false,
         // Fire webhook on failure of sniping invite (true/false)
         inviteFail: false
      },
      mentionEveryone: {
         // Mention on invalid code (true/false)
         codeInvalid: false,
         // Mention on already redeemed code (true/false)
         codeAlreadyRedeemed: false,
         // Mention on sniped code (true/false)
         codeSuccess: true,
         // Mention on giveaway enter (true/false)
         giveawayEntered: false,
         // Mention on giveaway win (true/false)
         giveawayWin: true,
         // Mention on invite join (true/false)
         inviteJoin: false,
         // Mention on failure of sniping invite (true/false)
         inviteFail: false
      }
   }
}
```

### What platform are you seeing the problem on?

Repl.it

### Relevant log output if applicable.

```text
main.sh: line 1: wget: command not found
```

**Comment by Itzmefoxy** [comment]
Import From Github

1. goto https://replit.com/new
2. click "Import From Github"
3. copy this repository link
4. paste it
5. click import, and wait
6. after that you'll see "select language" on the right side of the project
7. search for "Bash"
8. you'll see "configure the run button", enter it with "bash main.sh"
9. click done
10. follow steps from https://github.com/slow/nitro-sniper/wiki/Installation at the adding Environment Variables

still not working? tell me ⤵

**Comment by backvia** [comment]
new error with import
> Error: Cannot find module 'discord.js
Require stack:
- /home/runner/nitro-sniper/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/nitro-sniper/src/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/nitro-sniper/src/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nitro-sniper@1.5.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nitro-sniper@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-21T17_20_17_238Z-debug.log
exit status 1

**Comment by backvia** [comment]
- Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/nitro-sniper/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/nitro-sniper/src/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/nitro-sniper/src/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nitro-sniper@1.5.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nitro-sniper@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-21T17_20_17_238Z-debug.log
exit status 1

**Comment by backvia** [comment]
help me im stupid
`Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/nitro-sniper/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/nitro-sniper/src/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/nitro-sniper/src/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nitro-sniper@1.5.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nitro-sniper@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-21T17_20_17_238Z-debug.log
exit status 1`

**Comment by Itzmefoxy** [comment]
try 'npm i discord.js' at the console

**Comment by Vuxst** [comment]
Thank you. I would appreciate it if you could tell me what is happening and how I can fix it.  

> nitro-sniper@1.5.0 start /home/runner/nitro-sniper-3
> node .

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/nitro-sniper-3/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/nitro-sniper-3/src/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/nitro-sniper-3/src/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nitro-sniper@1.5.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nitro-sniper@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-22T02_31_43_054Z-debug.log
exit status 1

**Comment by TheKidCottons** [comment]
I am having trouble getting the link from this repository to work. Every time I put it into the "+ Import From GitHub", its says, "This repository could not be accessed." Any help?

**Comment by aboodstillplayz** [comment]
unfortunately i also have the same problem
