### ISSUE TITLE
invalid settings object

### ISSUE THREAD

**Issue by DarkGD123** [slow/nitro-sniper#35]
i put every details correctly and this pops up.
`[2021-02-23 06:38:00] Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process...`

**Comment by DarkGD123** [comment]
nevermind fixed it

**Comment by kelukelol** [comment]
Wait, @DarkGD123 , how did you fix it?

**Comment by DarkGD123** [comment]
> Wait, @DarkGD123 , how did you fix it?

I used the default config in the READme.md

**Comment by slow** [comment]
The config in the `README.md` is only to be used for reference, you shouldn't replace it with the variables that are already there. The one in the README just explains everything.

**Comment by DarkGD123** [comment]
yeah ik
