### ISSUE TITLE
[Bug] Code and type status are swapped in the webhook

### ISSUE THREAD

**Issue by bonxz** [slow/nitro-sniper#38]
**Describe the bug**
Code and type status are swapped in the webhook

**Expected behavior**

**Screenshots**
![snipe](https://user-images.githubusercontent.com/61289944/108899309-9372d080-7618-11eb-974b-1fb69b5b0511.png)

**Comment by Tropixi** [comment]
What is that cause i don't remember type being added?

**Comment by NightRaider73** [comment]
I still can't figure out how to get webhooks to work.  I am not sure if it is permissions or text file configs.

**Comment by slow** [comment]
> I still can't figure out how to get webhooks to work. I am not sure if it is permissions or text file configs.

![Image](https://media.wtf/99077885)

To set the webhook, you need to put its URL that you got from the webhook you made into the url variable.
You have customizability on when the webhook triggers as seen at the bottom. 
You also have the option to enable pings for certain events when the webhook fires.

**Comment by NightRaider73** [comment]
"webhook": {
    "https://discord.com/api/webhooks/813798984354496613/jQQXJ30VIhAPa6YiXqUhBRFcHsLG-q5Z": "*true",
    "enabled": {
      "codeInvalid": true,
      "codeAlreadyRedeemed": true,
      "codeSuccess": true,
      "giveawayEntered": true,
      "giveawayWin": true,
      "inviteJoin": true
    },
    "mentionEveryone": {
      "codeInvalid": false,
      "codeAlreadyRedeemed": false,
      "codeSuccess": true,
      "giveawayEntered": false,
      "giveawayWin": true,
      "inviteJoin": false
    }
  }
}


I changed the webhook for obvious reasons.

*I have put true in this section and left blank and it doesn't work.  It might also be because I run it on heroku.

**Comment by slow** [comment]
You are replacing the wrong link.
This is where the link should be.
![DC02F9A8-0D74-4CDF-B953-001F3D21B83D](https://user-images.githubusercontent.com/73202350/109324843-209e6b00-784d-11eb-9b52-f114f670da42.jpeg)

**Comment by NightRaider73** [comment]
Ah ok now I see
