### ISSUE TITLE
"Token does not have a billing source"

### ISSUE THREAD

**Issue by Fredric27** [slow/nitro-sniper#39]
When i turn on the sniper, it gives me a message:"Main token does not have a billing source, some codes will not be sniped". 
How can i resolve it?

**Comment by DarkGD123** [comment]
It means your account doesnt have a credit card or a payment method

**Comment by DarkGD123** [comment]
Add a credit card/payment method to remove the notification, without it you wont get some of the nitros that required credit card/payment method, but the sniper still works either way
