### ISSUE TITLE
Why does it connect via my alt and not my main? (the servers are only connected to on my alt and not main)[Bug] 

### ISSUE THREAD

**Issue by ohDevin** [slow/nitro-sniper#4]
**Describe the bug**
When I start the thing, why does it pop up as it being connected to my alt instead of my main?

**Comment by slow** [comment]
Your alt is used to listen for codes, your main accounts token only ever gets used when a code is being redeemed, there's many checks in place that stop the request from being fired and fake code detection to avoid bans. It never actually logs into your main account, it logs into your alt and as soon as the listener on your alt finds a code it redeems it with your main account.

**Comment by slow** [comment]
That being said, test it and make sure its working by sending a message to your alt containing a `discord.gift/ksakakkakakaakakakak` link.

**Comment by slow** [comment]
Check the previous issue you created, i replied there.

**Comment by ohDevin** [comment]
wait why is it saying "invalid main token" now?

**Comment by slow** [comment]
Your main token is invalid, get it again and set it in heroku settings again, this can be accessed by going to `Settings > Reveal Config Vars` and use the pencil to edit it.

Easy way of getting your token:
- CTRL + Shift + I
- Head to console
- Paste this: https://gist.github.com/slow/7771a228bc732dd46d5ea183e943ca69 and click enter.

**Comment by ohDevin** [comment]
worked, thanks!
