### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by LiGmA28** [slow/nitro-sniper#43]
**Is your feature request related to a problem? Please describe.**
does not dm if won a giveaway when rerolled

**Describe the solution you'd like**
send dm to giveaway hoster also when rerolled

**Additional context**

**Comment by IWolfZ** [comment]
Seems like a good idea

**Comment by slow** [comment]
Sadly this isn't possible.

When a giveaway winner is announced, the GiveawayBot attaches a message link at the bottom of its message.

It sadly doesn't do this when re-rolling a winner, making it impossible to know what giveaway you won.

**Comment by Vortecked** [comment]
slow, is it possible to have it dm the giveaway host when you are pinged? maybe it can search for the person who did the reroll command?
