### ISSUE TITLE
How long does it take for the Heroku app for nitro to run?

### ISSUE THREAD

**Issue by Disco-Smoothie** [slow/nitro-sniper#45]
**It's been on the "logged in..." for a long time**

It's been like
>[2021-02-28 04:23:05] Logged in with 2 accounts and 20 servers.

for quite a while. What should I do?

Here's a screenshot from the Heroku app:
![Screenshot 2021-02-28 12 14 58 AM](https://user-images.githubusercontent.com/79620096/109408709-056d5180-795a-11eb-93a6-26d6cfaf426c.png)

**Comment by DarkGD123** [comment]
Just wait of course

**Comment by DarkGD123** [comment]
Sniping nitro might take some time or days

**Comment by slow** [comment]
20 servers is way too low, join more servers and have at least 100 servers.
