### ISSUE TITLE
Invalide Settings Object

### ISSUE THREAD

**Issue by Sketcheads** [slow/nitro-sniper#49]
Getting the error "Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process..." when everything seems right, i even copied the default configurations from the Readme and changed the tokens and webhook variables and still getting the same error.

**Comment by Tropixi** [comment]
Smh don't copy the config in readme copy the one in the .env file the one in readme is only for show and design.

**Comment by Tropixi** [comment]
> Getting the error "Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process..." when everything seems right, i even copied the default configurations from the Readme and changed the tokens and webhook variables and still getting the same error.

https://raw.githubusercontent.com/slow/nitro-sniper/main/.env
