### ISSUE TITLE
Is this a feature? Does this run offline 24/7? [Feature Request] 

### ISSUE THREAD

**Issue by ohDevin** [slow/nitro-sniper#5]
title

**Comment by slow** [comment]
It runs 24/7 as long as you have the heroku `worker` dyno turned on. You could go outside, shut down your pc and do whatever you'd like and it will still run.

**Comment by slow** [comment]
Your dynos should look like this.
![Example](https://media.wtf/73259642)

**Comment by ohDevin** [comment]
oh okay thanks!

do you have a discord? ill add you so its easy access to dm you questions

**Comment by slow** [comment]
Yep, check my bio.
