### ISSUE TITLE
Running the nitro sniper locally help

### ISSUE THREAD

**Issue by inverspe** [slow/nitro-sniper#51]
When I run git clone https://github.com/slow/nitro-sniper nitro-sniper on cmd it says 'git' is not recognized as an internal or external command, operable program or batch file.

Same applies with nodejs terminal when I type it it just says "Uncaught SyntaxError: Unexpected identifier"

please help me

**Comment by Tropixi** [comment]
Download git bash
https://git-scm.com/downloads

**Comment by inverspe** [comment]
> Download git bash
> https://git-scm.com/downloads

thanks
