### ISSUE TITLE
"no main account token provided, exiting process"

### ISSUE THREAD

**Issue by Vortecked** [slow/nitro-sniper#54]
I am pretty sure I did everything correctly, i put in my token in the place i am supposed to. any help would be appreciated!

**Comment by Vortecked** [comment]
oh also i just remembered, after doing npm install, a bunch of error messages come up saying something about finding python. i am doing this on a git command prompt

**Comment by johna3212** [comment]
You need to add token in .env under tokens:main

Can you send screenshot for those errors

**Comment by Vortecked** [comment]
i did add the token tho. it looks like this "tokens":{"main":"*insert token*", "alts":[""]
and im gonna screenshot the error messages here:
![image](https://user-images.githubusercontent.com/71997442/112337895-9397d780-8c7b-11eb-8fb7-e470a0876643.png)
![image](https://user-images.githubusercontent.com/71997442/112337902-94c90480-8c7b-11eb-8f32-db7ca7a1f0a4.png)
![image](https://user-images.githubusercontent.com/71997442/112337905-95619b00-8c7b-11eb-91f2-6e5783cf9b04.png)
all of this shows up when I do npm install

**Comment by Vortecked** [comment]
anyone help?

**Comment by slow** [comment]
I wouldn't recommend running it locally as you'll have high ping, run it on heroku as all dependencies will be installed without an issue.

If you want to use it locally, install VS Build tools: https://www.npmjs.com/package/windows-build-tools

**Comment by Vortecked** [comment]
wait how do i run it on heroku
