### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by legendary0001** [slow/nitro-sniper#55]
webhook is not working

**Comment by Vortecked** [comment]
can you put screenshots/more information

**Comment by legendary0001** [comment]
ok 
![image](https://user-images.githubusercontent.com/76104734/112355535-c382c180-8cf3-11eb-99e1-7e6515a10af1.png)
i

**Comment by legendary0001** [comment]
![Uploading Screenshot_2021-03-24-22-54-20-87_572064f74bd5f9fa804b05334aa4f912.jpg…]()

**Comment by slow** [comment]
If you're deploying it on heroku, you need to modify the heroku environment variables and not the .env file.

**Comment by legendary0001** [comment]
How can i

**Comment by slow** [comment]
When you click the deploy to heroku button, the settings will be shown under the application name, edit them there.

**Comment by legendary0001** [comment]
I made a another repo then deployed it xD

**Comment by slow** [comment]
Well that means your environment variables aren't set, use the deploy button found under the installation section of the README.
