### ISSUE TITLE
[Feature Request] Does this work with other discord bots or just GiveawayBot?

### ISSUE THREAD

**Issue by Vortecked** [slow/nitro-sniper#56]
I tried to test this with Santa Lunar (one that I usually use) and it does not work. Does this only work with GiveawayBot? If so, can you add support for most of the other discord bots that are used for giveaways? (Invite Tracker, Prism, Plasma, etc,)

**Comment by slow** [comment]
Currently, it works with GiveawayBot. 

Support is planned for other bots.

**Comment by slow** [comment]
In fact, I will allow bots to be suggested on this issue.

Follow this format:
```
Bot Tag: Bot#0001
Bot ID: 1234567
Invite Link: https://discord.com/
Default Prefix & Giveaway Start Command: g!start
```

**Comment by joao44289** [comment]
Bot Tag: tip.cc#7731
Bot ID: 617037497574359050
Invite Link: https://discordapp.com/oauth2/authorize?client_id=617037497574359050&scope=bot%20applications.commands&permissions=344128
Default Prefix & Giveaway Start Command: $airdrop

**Comment by finaviggo** [comment]
Bot Tag: Giveaways#8717
Bot ID: 651627261782523926
Invite Link: https://discord.com/oauth2/authorize?client_id=651627261782523926&permissions=379968&scope=bot
Default Prefix & Giveaway Start Command: %start <duration> [winners] <prize>

**Comment by Zorral** [comment]
Bot Tag: Noumenon#7110
Bot ID: 758068429021249557
Invite Link: https://discordapp.com/oauth2/authorizeclient_id=617037497574359050&scope=bot%20applications.commands&permissions=344128
Default Prefix & Giveaway Start Command: !g start
