### ISSUE TITLE
[Bug] How Do i Open Or Use The Sniper

### ISSUE THREAD

**Issue by EddiePixeled** [slow/nitro-sniper#59]
Please Explain It Clearly

**Comment by S7RL7SAbsPfLB8tS** [comment]
https://github.com/slow/nitro-sniper/wiki/Installation

**Comment by EddiePixeled** [comment]
![Screenshot (54)](https://user-images.githubusercontent.com/81557577/112834231-bf70ee00-90bd-11eb-9694-314194e97e90.png)
how do i fix this @S7RL7SAbsPfLB8tS

**Comment by EddiePixeled** [comment]
dm me on discord YoJaaxk#7209

**Comment by slow** [comment]
The error is clear, read what it says.
