### ISSUE TITLE
[Question] Multiple Alts

### ISSUE THREAD

**Issue by 2Gritz** [slow/nitro-sniper#60]
How do I add more than one alt account? 
I keep getting the error invalid settings object

The beginning of my config is (tokens replaced with X) 
{
  "tokens": {
    "main": "X",
    "alts": [
      "X" "X"
    ]
  } 

It works when I just put only one alt account but I don't know how to do multiple
Thanks

**Comment by slow** [comment]
```json
alts: [
  "alt1",
  "alt2",
  "alt3"
]
```
