### ISSUE TITLE
[Bug] Heroku Account suspend bug up again

### ISSUE THREAD

**Issue by bonxz** [slow/nitro-sniper#66]
![account](https://user-images.githubusercontent.com/61289944/115255691-cde77e00-a12e-11eb-88c3-5e3529ccb59d.png)

**Comment by 2Gritz** [comment]
Yeah i got suspended to :(

**Comment by 2Gritz** [comment]
I made a new account and it got suspended the next day.

**Comment by 2Gritz** [comment]
I got unbanned

**Comment by bonxz** [comment]
> I got unbanned

How?

**Comment by 2Gritz** [comment]
> > I got unbanned
> 
> How?

They said they banned a ton of free accounts as an error and they unbanned me. If you didn't get unbanned appeal the ban and tell them you didn't do anything wrong.

**Comment by frosDfurret** [comment]
If you don't get unbanned, you can make a burner account using a temp mail service, then just save the credentials so you don't lose them. I used 15minutemail.email but it seems to be down. Note that not all work, as Heroku likely banned a lot of the email domains.

**Comment by slow** [comment]
I'm guessing this was an error on Heroku's end so I will close this, if anyone else gets suspended open another issue and I'll look into it.
