### ISSUE TITLE
Can you host multiple alt tokens?

### ISSUE THREAD

**Issue by PiggyAwesome** [slow/nitro-sniper#73]
Hello, I was wondering if it is possible to use more than just one token at the alt section sothat you can use more than 2 accounts to react and snipe.

**Comment by Tropixi** [comment]
Yes

**Comment by frosDfurret** [comment]
> Hello, I was wondering if it is possible to use more than just one token at the alt section sothat you can use more than 2 accounts to react and snipe.

yes, but be warned; i used 6 alts (i'm desperate) and all 6 of them got banned after 24 hours.

**Comment by PiggyAwesome** [comment]
Can someone please demonstrate how, I get errors when i try to do this:

```
"token"
"token",
"token", 
```

**Comment by frosDfurret** [comment]
> Can someone please demonstrate how, I get errors when i try to do this:
> 
> ```
> "token"
> "token",
> "token", 
> ```

The correct format is
"token",
"token",
"token"
All tokens should end with a comma, except for the last one. Cheers.
