### ISSUE TITLE
Low reaction time

### ISSUE THREAD

**Issue by V4NSH4J** [slow/nitro-sniper#82]
Heya, firstly I want to thank you for this, It works like a charm. I was wondering how I could reduce the time taken to snipe the code on heroku. Currently getting 300ms - 800ms .. Any tips appreciated :)

**Comment by snuckdev** [comment]
Yeah, same here. When I use NitroSniperGo I get 40-70ms.

**Comment by dariot99** [comment]
Try changing region of the server, it's all matter of when the sniper is hosted and what's the region of the servers you're into. (Example: sniper running in US West will have low delay when sniping codes from Discord servers which region is set to US West)

**Comment by slow** [comment]
As @dariot99 said, there's plenty of factors that affect speed. The sniper is designed to work the fastest it can considering it is provided with proper resources such as a good server location & decent internet speed.
