### ISSUE TITLE
[Feature Request] can there be an .exe version of this sniper?

### ISSUE THREAD

**Issue by youtube-yt-github** [slow/nitro-sniper#83]
I don't think I have js installed. an .exe would be greatly appreciated :D
also the .env file shows up as one loooooooong line for  me on visual studio code. don't know why

**Comment by dariot99** [comment]
It's normal that the .env files shows up like that, just don't mess up while editing it and everything will be fine.
For the rest, all you have to do to run it is download Node.js (v14.16 is fine) and Git, then simply follow the instructions in the wiki: https://github.com/slow/nitro-sniper/wiki/Installation

If you want, you could make a simple .bat file that when opened auto-starts the sniper, here's the one I made:

`cd C:\...\nitro-sniper
node .`

change the file path with the one where you nitro-sniper folder is located and save the txt file as start.bat
