### ISSUE TITLE
[Feature Request] A way to make Sniper 24/7 

### ISSUE THREAD

**Issue by WSrujan** [slow/nitro-sniper#86]
Is there way to run this sniper 24/7 without keeping pc on?
for eg hosting on a server

**Comment by dariot99** [comment]
Just rent a VPS and host it there or deploy it on Heroku. I'm currently running it on a VPS

**Comment by snuckdev** [comment]
Use heroku. The button is available at https://github.com/slow/nitro-sniper/wiki/Installation
