### ISSUE TITLE
not detecting any snipes

### ISSUE THREAD

**Issue by ohDevin** [slow/nitro-sniper#9]
doesnt detect any snipes

the heroku works fine, it loads up fine, the alt token logs in fine, but when i put in a test code, it doesn't detect it.

**Comment by slow** [comment]
Code has to be between 16-25 characters in length to be considered a real code.

It works fine for me on the latest commit. 
![6BACD004-C17A-492B-9B79-35D97370E4A0](https://user-images.githubusercontent.com/73202350/105628107-d7649100-5e32-11eb-9dad-e1431c012457.png)
