### ISSUE TITLE
High latency (not normal I think)

### ISSUE THREAD

**Issue by snuckdev** [slow/nitro-sniper#91]
I'm getting like 1000ms or even 2300ms with Heroku located in United States, but with my old sniper (NitroSniperGo) I get like 50ms-70ms. I think this isn't normal.

**Comment by dariot99** [comment]
Try changing region on Heroku, make sure that the servers you're sniping into are USA region too. Better, spend 5 bucks and rent a VPS, I'm running the sniper on a VPS located in Los Angles and I get 100-150ms latency, tonight I sniped a code at 148ms, when I join servers I make sure there region is set to USA.
