### ISSUE TITLE
[Feature Request] Add more tokens

### ISSUE THREAD

**Issue by Kromback** [slow/nitro-sniper#94]
**Is your feature request related to a problem? Please describe.**
Hi, I was trying to add more tokens from another account and every time I add it as second in alt it tells me that there is an error that I look at the backup gihub

**Describe the solution you'd like**
I would like to know how to enter other tokens, I recently downloaded the file so I imagine I will have the latest update.
**Additional context**
Nice

**Comment by editsellar** [comment]
Have you put the token format like:

"Token", "Token",  "Token", etc.

**Comment by Kromback** [comment]
Invalid settings object, if you require more help visit https://github.com/slow/nitro-sniper#default-configuration for an example. Exiting process...


This appears to me and I have it well on, do you know why it can be?

**Comment by slow** [comment]
```
alts: [
   "token1",
   "token2",
   "token3"
]
```
