### ISSUE TITLE
[Bug] Invite sniper min and max time not working

### ISSUE THREAD

**Issue by editsellar** [slow/nitro-sniper#96]
The invite sniper minimum and maximum area does not work for me, when I change the min and max the invite sniper just completely doesn't work.

Might be an issue with me but it didn't work for my friend either, hosted on Heroku.

**Comment by Jorgen10** [comment]
I have an issue with the invite sniper in general even if i havent changed on it

**Comment by InimicalPart** [comment]
What did you set the `min` and `max` to? Would you mind sending the contents of your .env file? Remember to remove all tokens and webhook links before sending!

**Comment by slow** [comment]
Fixed in e166fa304445143c4206010caf148080f508f68d
